version: "3"
networks:
  tunnel:

services:
   # IPFS Gateway
  ipfs:
   hostname: ipfs
   image: sonrhq/ipfs:latest
   ports:
     - 4001:4001 # rest
     - 5001:5001 # p2p
     - 8080:8080 # gateway
   volumes:
     - /mnt/disks/ipfs_data:/root/.ipfs
   networks:
    - tunnel
