version: "3"
networks:
  tunnel:
    external: true

services:
  # Cloudflared Reverse Proxy
  cloudflared:
    image: erisamoe/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${MATRIX_TUNNEL_TOKEN}
    networks:
      - tunnel

  # Sonr Validator
  sonrd:
    init: true
    container_name: sonrd
    hostname: sonrd
    image: sonrd-runner:latest
    command: ["start"]
    volumes:
     - /mnt/vol_sonr:/root/.sonr
    ports:
      - 1317:1317 # rest
      - 26657:26657 # rpc
      - 9090:9090 # grpc
    restart: always
    networks:
      - tunnel
