# .github/bump.yml
release:
  title-prefix: "v"
  initial-version: "v0.0.1"
  tag-prefix: "v"
branch:
  version-branch-prefix: "v"
  create-minor-version-branch: true
  create-major-version-branch: true
categories:
  - title: "Breaking Changes!"
    labels:
      - "BreakingChange"
    commits:
      - "breaking"
    changes-prefix: ":warning: "
  - title: "Changes"
    labels:
      - "Feature"
    commits:
      - "feat"
    changes-prefix: ":gift: "
  - title: "Changes"
    labels:
      - Maintenance
    commits:
      - "chore"
    changes-prefix: ":hammer: "
  - title: "Bug Fixes"
    labels:
      - "Bug"
    commits:
      - "fix"
    changes-prefix: ":ambulance: "
  - title: "Changes"
    labels:
      - "Documentation"
    commits:
      - "document"
    changes-prefix: ":blue_book: "
  - title: "Dependency Updates"
    labels:
      - "Dependencies"
    skip-label: "Development"
    commits:
      - "dependency"
    changes-prefix: ":green_book: "
bump:
  default: "patch"
  major:
    labels:
      - "BreakingChange"
    commits:
      - "breaking"
  minor:
    labels:
      - "Feature"
      - "Dependencies"
    commits:
      - "feat"
  patch:
    labels:
      - "Bug"
      - "Documentation"
      - "Maintenance"
    commits:
      - "fix"
      - "test"
      - "chore"
files:
  file-path: "CHANGELOG.md"
  line: 1
  start: 3
