# .github/bump.yml
release:
  title-prefix: "v"
  initial-version: "v0.0.1"
  tag-prefix: "v"
branch:
  version-branch-prefix: "v"
  create-minor-version-branch: true
  create-major-version-branch: true
categories:
  - title: "Breaking Changes!"
    labels:
      - "Breaking Changes"
    changes-prefix: ":warning: "
  - title: "Changes"
    labels:
      - "Feature"
    commits:
      - "feat"
  - title: "Changes"
    labels:
      - Maintenance
    commits:
      - "chore"
  - title: "Bug Fixes"
    labels:
      - "Bug"
    commits:
      - "fix"
  - title: "Changes"
    labels:
      - "Documentation"
    commits:
      - "document"
  - title: "Dependency Updates"
    labels:
      - "Dependencies"
    commits:
      - "dependency"
bump:
  default: "patch"
  major:
    labels:
      - "Major"
    commits:
      - "breaking"
  minor:
    labels:
      - "Feature"
      - "Dependencies"
      - "Minor"
    commits:
      - "feat"
  patch:
    labels:
      - "Bug"
      - "Documentation"
      - "Maintenance"
      - "Patch"
    commits:
      - "fix"
      - "test"
      - "documentation"
files:
  file-path: "CHANGELOG.md"
  line: 1
  start: 3
