version: "3"

tasks:
  default:
    desc: "Builds the project for current platform"
    cmds:
      - earthly --no-sat +build
      - task: sonrd-docker
      - task: hway-docker

  sonrd-docker:
    desc: "Builds the project for current platform"
    cmds:
      - cp ./bin/sonrd ./deploy/
      - docker build -t sonrhq/sonrd:latest -f ./deploy/Dockerfile.node ./deploy

  hway-docker:
    desc: "Builds the project for current platform"
    cmds:
      - cp ./bin/hway ./deploy/
      - docker build -t sonrhq/hway:latest -f ./deploy/Dockerfile.hway ./deploy
