version: "3"
dir: ../
# -----------------------------------------------------------------------------
# -- Project Config ------------------------------------------------------------
# -----------------------------------------------------------------------------
vars:
  VERSION:
    sh: echo $(git describe --tags --abbrev=0)
    default: "v0.0.0"
  COMMIT:
    sh: git log -n 1 --format=%h
    default: "0000000"
  DATE:
    sh: date -u '+%m/%d/%y %I:%M:%S%p'
    default: "1970-01-01_00:00:00AM"
  REGISTRY: ghcr.io/sonrhq

# ----------------------------------------------------------------------------
# -- Public Tasks ------------------------------------------------------------
# ----------------------------------------------------------------------------
tasks:
  default:
    desc: Build the binary for mac, linux
    cmds:
      - task: go-build
        vars:
          OS: linux
          ARCH: amd64
      - task: go-build
        vars:
          OS: linux
          ARCH: arm64
      - task: go-build
        vars:
          OS: darwin
          ARCH: amd64

  release:
    desc: Build the binary for docker
    depends: [build]
    cmds:
      - task: docker-release
        vars:
          IMAGE: sonr-base
      - task: docker-release
        vars:
          IMAGE: sonr-node

  release:vals:
    desc: Release validator docker images
    cmds:
      - task: docker-release-val
        vars:
          TOKEN: $DOPPLER_VAL_DOCKER_TOKEN
          MONIKER: mason

  release:deps:
    desc: Release support dependencies
    cmds:
      - task: docker-release
        vars:
          IMAGE: tkms
      - task: docker-release
        vars:
          IMAGE: sonr-faucet
          
# ------------------------------------------------------------------------------
# -- Internal Tasks ------------------------------------------------------------
# ------------------------------------------------------------------------------
  docker-release:
    silent: true
    internal: true
    desc: Build, tag and push the docker image
    cmds:
      - docker build -f ./Dockerfile . --no-cache --target {{.IMAGE}} -t {{.IMAGE}}
      - docker tag {{.IMAGE}} {{.REGISTRY}}/{{.IMAGE}}:latest
      - docker tag {{.IMAGE}} {{.REGISTRY}}/{{.IMAGE}}:{{.VERSION}}
      - docker tag {{.IMAGE}} {{.REGISTRY}}/{{.IMAGE}}:{{.COMMIT}}
      - docker push {{.REGISTRY}}/{{.IMAGE}}:latest
      - docker push {{.REGISTRY}}/{{.IMAGE}}:{{.VERSION}}
      - docker push {{.REGISTRY}}/{{.IMAGE}}:{{.COMMIT}}
    requires:
      vars: [IMAGE]

  docker-release-val:
    silent: true
    internal: true
    desc: Build, tag and push the docker image
    cmds:
      - docker build --build-arg "DOPPLER_TOKEN={{.TOKEN}}" -f ./Dockerfile . --no-cache --target sonr-validator -t sonr-val-{{.MONIKER}}
      - docker tag sonr-val-{{.MONIKER}} {{.REGISTRY}}/sonr-val-{{.MONIKER}}:latest
      - docker tag sonr-val-{{.MONIKER}} {{.REGISTRY}}/sonr-val-{{.MONIKER}}:{{.VERSION}}
      - docker tag sonr-val-{{.MONIKER}} {{.REGISTRY}}/sonr-val-{{.MONIKER}}:{{.COMMIT}}
      - docker push {{.REGISTRY}}/sonr-val-{{.MONIKER}}:latest
      - docker push {{.REGISTRY}}/sonr-val-{{.MONIKER}}:{{.VERSION}}
      - docker push {{.REGISTRY}}/sonr-val-{{.MONIKER}}:{{.COMMIT}}
    requires:
      vars: [TOKEN, MONIKER]


  go-build:
    silent: true
    internal: true
    desc: Build the go binary
    cmds:
      - mkdir -p ./build/sonrd-{{.OS}}-{{.ARCH}}
      - GOOS={{.OS}} GOARCH={{.ARCH}} go build -o ./build/sonrd-{{.OS}}-{{.ARCH}}/sonrd ./cmd/sonrd
      - cp ./scripts ./build/sonrd-{{.OS}}-{{.ARCH}}/scripts -p
    requires:
      vars: [OS,ARCH]
