version: "3"

tasks:
  all:
    desc: "Run all build tasks"
    cmds:
      - rm -rf ./bin
      - task: sonrd
      - task: hway
      - task: dendrite

    dendrite:
      cmds:
        - rm -rf ./tmp
        - git clone https://github.com/matrix-org/dendrite ./tmp/dendrite
        - cd ./tmp/dendrite && GOOS=linux GOARCH=amd64 go build -o ../../bin ./cmd/...
        - rm -rf ./bin/dendrite-demo-pinecone
        - rm -rf ./bin/dendrite-demo-yggdrasil
        - rm -rf ./bin/dendrite-upgrade-tests
        - rm -rf ./bin/furl
        - rm -rf ./bin/resolve-state
        - rm -rf ./tmp/dendrite

  hway:
    cmds:
      - templ generate
      - task: prisma-hway
      - task: prisma-indexer
      - task: prisma-matrix
      - GOOS=linux GOARCH=amd64 go build -o ./bin/hway ./cmd/hway

  hway:current:
    cmds:
      - templ generate
      - task: prisma-hway
      - task: prisma-indexer
      - task: prisma-matrix
      - go build -o ./bin/hway ./cmd/hway

  sonrd:
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o ./bin/sonrd ./cmd/sonrd

  # Helper tasks for generating Prisma client
  prisma-hway:
    internal: true
    dir: ./internal/prisma/hway
    cmd: go run github.com/steebchen/prisma-client-go generate

  prisma-indexer:
    internal: true
    dir: ./internal/prisma/indexer
    cmd: go run github.com/steebchen/prisma-client-go generate

  prisma-matrix:
    internal: true
    dir: ./internal/prisma/matrix
    cmd: go run github.com/steebchen/prisma-client-go generate
