version: "3"

tasks:
  default:
    desc: "Builds the project for current platform"
    cmds:
      - templ generate
      - rm -rf bin/ && mkdir ./bin/
      - go build -o ./bin/sonrd ./cmd/sonrd
      - rm -rf dist

  current:
    desc: "Builds the project for current platform"
    cmds:
      - task: sonrd
      - task: hway

  sonrd:
    desc: "Builds the project for current platform"
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o ./bin/sonrd ./cmd/sonrd
      - earthly --no-sat +current-node

  hway:
    desc: "Builds the project for current platform"
    cmds:
      - task: prisma-gen
      - GOOS=linux GOARCH=amd64 go build -o ./bin/hway ./cmd/hway
      - earthly --no-sat +current-hway

  devcontainer:
    desc: "Builds the project for current platform"
    cmds:
      - docker run -it --rm
        -v ./tmp/envbuilder:/workspaces
        -e GIT_URL=https://github.com/sonrhq/sonr
        -e INIT_SCRIPT=zsh
        ghcr.io/coder/envbuilder

  prisma-gen:
    dir: ./internal/prisma
    cmd: go run github.com/steebchen/prisma-client-go generate

  prisma-sync:
    dir: ./internal/prisma
    cmd: go run github.com/steebchen/prisma-client-go db push

  prisma-pull:
    dir: ./internal/prisma
    cmd: go run github.com/steebchen/prisma-client-go db pull

  prisma-dev:
    dir: ./internal/prisma
    cmd: go run github.com/steebchen/prisma-client-go migrate dev

  prisma-deploy:
    dir: ./internal/prisma
    cmd: go run github.com/steebchen/prisma-client-go migrae deploy
