project_name: sonr-core
builds:
  - id: sonr
    binary: sonr-node
    dir: cmd/full
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: binary
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  github:
    owner: sonr-io
    name: core
