# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json

project_name: sonrd
before:
  # Templates for the commands to be ran.
  hooks:
    - go mod download

builds:
  # Build Sonr Daemon
  - id: sonrd
    main: cmd/sonrd/main.go
    binary: sonrd
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X main.Version={{ .Version }}
      - -X main.Commit={{ .Commit }}
      - -w -s
kos:
  - repository: sonrhq/sonrd
    tags:
      - "{{.Version}}"
      - latest
    bare: false
    preserve_import_paths: true
    platforms:
      - linux/amd64
      - linux/arm64
      - darwin/amd64
      - darwin/arm64

archives:
  - id: sonrd
    builds:
      - sonrd
    name_template: "{{.Binary}}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
checksum:
  name_template: sha256sum.txt
  algorithm: sha256

brews:
  - folder: Formula
    caveats: "How to use this binary"
    homepage: "https://sonrhq.com"
    description: "Sonr Binary Node"
    ids:
      - "sonrd"
    license: "OpenGLV3"
    name: "sonrd"
    repository:
      owner: sonrhq
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
nfpms:
  - id: sonrd
    description: "Sonr Binary Node"
    maintainer: "Sonr Inc."
    homepage: "https://sonr.io"
    license: "OpenGLV3"
    formats:
      - deb

# ! ||--------------------------------------------------------------------------------||
# ! ||                              Release and Changelog                             ||
# ! ||--------------------------------------------------------------------------------||
release:
  github:
    owner: sonrhq
    name: sonr

  name_template: '🆔 Release {{ .Now.Format "2006.01.02" }}'
  mode: replace
  draft: false
  extra_files:
    - glob: ./assets/public/scripts/install.sh

changelog:
  sort: asc
  abbrev: -1
  groups:
    - title: Features
      regexp: .*?feat:.*$
      order: 0
    - title: Documentation
      regexp: .*?docs:.*$
      order: 1
    - title: Fixes
      regexp: .*?fix:.*$
      order: 2
    - title: Clean Up
      regexp: .*?chore:.*$
      order: 3
    - title: Others
      order: 999
furies:
  - account: sonr
