# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json

project_name: sonrd
before:
  # Templates for the commands to be ran.
  hooks:
    - go mod download
    - go install github.com/a-h/templ/cmd/templ@latest
    - templ generate

builds:
  # Build Sonr Daemon
  - id: sonrd
    main: cmd/sonrd/main.go
    binary: sonrd
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X main.Version={{ .Version }}
      - -X main.Commit={{ .Commit }}
      - -w -s

  # Build Highway Daemon
  - id: hway
    main: cmd/hway/main.go
    binary: hway
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

# ! ||--------------------------------------------------------------------------------||
# ! ||                                Tarball Archives                                ||
# ! ||--------------------------------------------------------------------------------||
archives:
  - id: sonrd
    builds:
      - sonrd
    name_template: "{{.Binary}}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
  - id: hway
    builds:
      - hway
    name_template: "{{.Binary}}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
checksum:
  name_template: sha256sum.txt
  algorithm: sha256

brews:
  - folder: Formula
    caveats: "How to use this binary"
    homepage: "https://sonrhq.com"
    description: "Sonr Binary Node"
    ids:
      - "sonrd"
    license: "OpenGLV3"
    name: "sonrd"
    repository:
      owner: sonrhq
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
  - folder: Formula
    ids:
      - "hway"
    caveats: "How to use this binary"
    homepage: "https://sonrhq.com"
    name: "hway"
    description: "Hway Binary Node"
    license: "OpenGLV3"
    repository:
      owner: sonrhq
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"

# ! ||--------------------------------------------------------------------------------||
# ! ||                              Release and Changelog                             ||
# ! ||--------------------------------------------------------------------------------||
release:
  github:
    owner: sonrhq
    name: sonr

  footer:
    from_file:
      path: ./.github/assets/release-footer.md

  name_template: '🆔 Release {{ .Now.Format "2006.01.23" }}'
  mode: replace
  draft: false
  extra_files:
    - glob: .github/assets/install.sh

changelog:
  sort: asc
  abbrev: -1
  groups:
    - title: Features
      regexp: .*?feat:.*$
      order: 0
    - title: Documentation
      regexp: .*?docs:.*$
      order: 1
    - title: Fixes
      regexp: .*?fix:.*$
      order: 2
    - title: Clean Up
      regexp: .*?chore:.*$
      order: 3
    - title: Others
      order: 999

nightly:
  name_template: '🌙 Nightly {{ .Now.Format "2006.01.23" }}'
  tag_name: nightly
  publish_release: true
  keep_single_release: true
