# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json

project_name: sonrd
builds:
  # Build Sonr Daemon
  - id: sonrd
    main: cmd/sonrd/main.go
    binary: sonrd
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X main.Version={{ .Version }}
      - -X main.Commit={{ .Commit }}
      - -w -s

# ! ||--------------------------------------------------------------------------------||
# ! ||                                Tarball Archives                                ||
# ! ||--------------------------------------------------------------------------------||
archives:
  - id: zipped
    builds:
      - sonrd
    name_template: "{{.ProjectName}}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
checksum:
  name_template: sha256sum.txt
  algorithm: sha256

brews:
  -
    folder: Formula
    caveats: "How to use this binary"
    homepage: "https://sonrhq.com"
    description: "Sonr Binary Node"
    license: "OpenGLV3"
    repository:
      owner: sonrhq
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"

kos:
  - repository: ghcr.io/sonrhq/sonrd
    main: ./cmd/sonrd
    tags:
    - '{{.Version}}'
    - latest
    bare: true
    preserve_import_paths: false
    platforms:
    - linux/amd64
    - linux/arm64

# ! ||--------------------------------------------------------------------------------||
# ! ||                              Release and Changelog                             ||
# ! ||--------------------------------------------------------------------------------||
release:
  github:
    owner: sonrhq
    name: sonr

  footer:
    from_file:
      path: ./.github/assets/release-footer.md

  name_template: "Sonr 🆔 | v{{.Version}}"
  mode: replace
  draft: false
  extra_files:
    - glob: scripts/install.sh

changelog:
  sort: asc
  abbrev: -1
  groups:
    - title: Features
      regexp: .*?feat:.*$
      order: 0
    - title: Documentation
      regexp: .*?docs:.*$
      order: 1
    - title: Fixes
      regexp: .*?fix:.*$
      order: 2
    - title: Clean Up
      regexp: .*?chore:.*$
      order: 3
    - title: Others
      order: 999

nightly:
  name_template: 'nightly-{{ .Now.Format "2006-01-02" }}'
  tag_name: nightly
  publish_release: true
  keep_single_release: true
