project_name: sonr-core
builds:
  - id: sonr
    binary: sonrd
    dir: cmd/daemon
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: binary
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  github:
    owner: sonr-io
    name: core
