# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
project_name: sonr
before:
  hooks:
    - go mod download

builds:
  # Build - hway
  - id: hway
    main: cmd/hway/main.go
    binary: hway
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X main.Version={{ .Version }}
      - -X main.Commit={{ .Commit }}
      - -w -s

dockers:
  # Docker Images - hway
  - image_templates:
      - ghcr.io/didao-org/hway:{{ .Version }}
      - ghcr.io/didao-org/hway:latest
      - "didao/hway:{{ .Version }}"
      - didao/hway:latest
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    ids:
      - hway
    dockerfile: ./deploy/Dockerfile.hway

archives:
  # Archives
  - id: hway
    builds:
      - hway
    name_template: "{{.Binary}}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz

checksum:
  name_template: sha256sum.txt
  algorithm: sha256

brews:
  # Homebrew - hway
  - folder: Formula
    caveats: "Run the Sonr Highway with `hway`"
    homepage: "https://sonr.io"
    description: "Highway is a Decentralized Gateway which serves the Sonr Dynamic UI and a gateway to the blockchain API."
    license: "OpenGLV3"
    name: "hway"
    ids:
      - "hway"
    repository:
      owner: sonrhq
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"

release:
  github:
    owner: didao-org
    name: sonr

  name_template: "Release {{ .Version }}"
  mode: replace
  draft: false

changelog:
  sort: asc
  abbrev: -1
  groups:
    - title: Features
      regexp: .*?feat:.*$
      order: 0
    - title: Documentation
      regexp: .*?docs:.*$
      order: 1
    - title: Fixes
      regexp: .*?fix:.*$
      order: 2
    - title: Clean Up
      regexp: .*?chore:.*$
      order: 3
    - title: Others
      order: 999
