# Project information.
project_name: sonrd

env:
  - COSMWASM_VERSION=v1.3.0

before:
  hooks:
    - rm -rf dist
    - go mod download
    - go mod verify
    - go mod tidy
    - go generate ./...
    - mkdir -p ./dist/{{ .Version }}

# The builds section.
builds:
  # Build - Darwin (amd64)
  - id: sonrd-darwin-amd64
    main: ./cmd/sonrd/main.go
    binary: sonrd
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvmstatic_darwin.a -O /lib/libwasmvmstatic_darwin.a
    env:
      - CC=o64-clang
      - CXX=o64-clang++
      - GOOS=darwin
      - GOARCH=amd64
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=sonr
      - -X github.com/cosmos/cosmos-sdk/version.AppName=sonrd
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,static_wasm
      - -w -s
      - -linkmode=external
    tags:
      - netgo
      - static_wasm

  # Build - Darwin (arm64)
  - id: sonrd-darwin-arm64
    main: ./cmd/sonrd/main.go
    binary: sonrd
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvmstatic_darwin.a -O /lib/libwasmvmstatic_darwin.a
    env:
      - CC=oa64-clang
      - CGO_LDFLAGS=-L/lib
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=sonr
      - -X github.com/cosmos/cosmos-sdk/version.AppName=sonrd
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,static_wasm
      - -w -s
      - -linkmode=external
    tags:
      - netgo
      - static_wasm

  # Build - Linux (amd64)
  - id: sonrd-linux-amd64
    main: ./cmd/sonrd
    binary: sonrd
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.COSMWASM_VERSION }}/libwasmvm_muslc.x86_64.a -O /usr/lib/x86_64-linux-gnu/libwasmvm_muslc.a
    flags:
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=sonr
      - -X github.com/cosmos/cosmos-sdk/version.AppName=sonrd
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,muslc
      - -w -s
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs -static'
    tags:
      - netgo
      - muslc
    env:
      - GOOS=linux
      - GOARCH=amd64
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - amd64

universal_binaries:
  - id: sonrd-darwin-universal
    ids:
      - sonrd-darwin-amd64
      - sonrd-darwin-arm64
    replace: true

archives:
  - id: zipped
    builds:
      - sonrd-darwin-universal
      - sonrd-linux-amd64
      - sonrd-linux-arm64
    name_template: "{{ .Version }}/{{.ProjectName}}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
  - id: binaries
    builds:
      - sonrd-darwin-universal
      - sonrd-linux-amd64
      - sonrd-linux-arm64
      - sonrd-darwin-amd64
      - sonrd-darwin-arm64
    name_template: "{{ .Version }}/{{.ProjectName}}-{{ .Os }}-{{ .Arch }}"
    format: binary

checksum:
  name_template: "sha256sum.txt"
  algorithm: sha256

# Docs: https://goreleaser.com/customization/changelog/
changelog:
  use: github
  abbrev: -1

# Docs: https://goreleaser.com/customization/release/
release:
  github:
    owner: sonrhq
    name: core
  replace_existing_draft: true
  header: |
    < DESCRIPTION OF RELEASE >

    ## Changelog

    See the full changelog [here](https://github.com/sonrhq/core/blob/v{{ .Version }}/CHANGELOG.md)

    ## ⚡️ Binaries

    Binaries for Linux and Darwin (amd64 and arm64) are available below.
    Darwin users can also use the same universal binary `sonrd-{{ .Version }}-darwin-all` for both amd64 and arm64.

    #### 🔨 Build from source

    If you prefer to build from source, you can use the following commands:

    ````bash
    git clone https://github.com/sonrhq/core
    cd core && git checkout v{{ .Version }}
    make build-darwin # or make build-linux
    ````

    ## 🐳 Run with Docker

    As an alternative to installing and running sonrd on your system, you may run sonrd in a Docker container.
    The following Docker images are available in our registry:

    | Image Name                              | Base                                 | Description                       |
    |-----------------------------------------|--------------------------------------|-----------------------------------|
    | `sonrhq/core:{{ .Version }}`            | `distroless/static-debian11`         | Default image based on Distroless |
    | `sonrhq/core:{{ .Version }}-distroless` | `distroless/static-debian11`         | Distroless image (same as above)  |
    | `sonrhq/core:{{ .Version }}-nonroot`    | `distroless/static-debian11:nonroot` | Distroless non-root image         |
    | `sonrhq/core:{{ .Version }}-alpine`     | `alpine`                             | Alpine image                      |

    Example run:

    ```bash
    docker run sonrhq/sonrd:{{ .Version }} version
    # v{{ .Version }}
    ````

    All the images support `arm64` and `amd64` architectures.

  name_template: "Sonr Core - v{{.Version}} 🆔"
  mode: replace
  draft: true
