# Project information.
project_name: sonrd
release:
  github:
    owner: sonrhq
    name: core

# The prebuild section.
before:
  hooks:
    - go mod download
    - go mod verify
    - go mod tidy
    - go generate ./...

# The builds section.
builds:
  - id: "sonrd"
    main: ./cmd/sonrd
    binary: sonrd
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    flags:
      - -ldflags=-w -s -extldflags "-static" -X github.com/cosmos/cosmos-sdk/version.Name=sonr -X github.com/cosmos/cosmos-sdk/version.AppName=sonrd -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }} -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }} -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger"
    env:
      - CGO_ENABLED=0

# The archives section.
archives:
  - id: "archive"
    builds:
      - sonrd
    format: tar.gz
    files:
      - LICENSE*
      - README.md
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

# The checksum section.
checksum:
  name_template: 'checksums.txt'

# The nfpm section.
nfpms:
  - vendor: Sonr Inc.
    homepage: https://sonr.io
    maintainer: Prad Nukala <prad@sonr.io>
    description: Sonr is a peer-to-peer identity and asset management system that leverages DID documents, Webauthn, and IPFS — providing users with a secure, user-friendly way to manage their digital identity and assets.
    license: Your License
    formats:
      - deb
      - rpm
    contents:
      - src: "./**/*.md"
        dst: "/usr/local/doc/core/"
      - src: "./**/*.txt"
        dst: "/usr/local/doc/core/"

# The snapcraft section.
snapcrafts:
-
  name_template: '{{ .ProjectName }}_{{ .Version }}'
  publish: true
  summary: Sonr is a cosmos based blockchain.
  description: Sonr is a peer-to-peer identity and asset management system that leverages DID documents, Webauthn, and IPFS — providing users with a secure, user-friendly way to manage their digital identity and assets.
  name: sonr
kos:
-
  id: sonrd
  build: sonrd
  main: ./cmd/sonrd
  working_dir: .
  base_image: alpine
  labels:
    org.opencontainers.image.created: '{{ .Date }}'
    org.opencontainers.image.title: '{{ .ProjectName }}'
    org.opencontainers.image.version: '{{ .Tag }}'
    org.opencontainers.image.source: 'https://github.com/sonrhq/core'
  repository: ghcr.io/sonrhq/sonrd
  platforms:
  - linux/amd64
  - linux/arm64
  tags:
  - latest
  - '{{ .Tag }}'
  sbom: none
  bare: true
