# Project information.
project_name: sonrd

env:
  - WASMVM_URL=https://github.com/CosmWasm/wasmvm/releases/download/v1.3.0

before:
  hooks:
    - go mod download

# ! ||--------------------------------------------------------------------------------||
# ! ||                                     Builds                                     ||
# ! ||--------------------------------------------------------------------------------||
builds:
  # Build - Linux (amd64)
  - id: sonrd-linux-amd64
    main: ./cmd/sonrd
    binary: sonrd
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=sonr
      - -X github.com/cosmos/cosmos-sdk/version.AppName=sonrd
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -w -s

  # Build - Linux (arm64)
  - id: sonrd-linux-arm64
    main: ./cmd/sonrd
    binary: sonrd
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=sonr
      - -X github.com/cosmos/cosmos-sdk/version.AppName=sonrd
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -w -s

  # Build - Darwin (amd64)
  - id: sonrd-darwin-amd64
    main: ./cmd/sonrd/main.go
    binary: sonrd
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=sonr
      - -X github.com/cosmos/cosmos-sdk/version.AppName=sonrd
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -w -s

  # Build - Darwin (arm64)
  - id: sonrd-darwin-arm64
    main: ./cmd/sonrd/main.go
    binary: sonrd
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X github.com/cosmos/cosmos-sdk/version.Name=sonr
      - -X github.com/cosmos/cosmos-sdk/version.AppName=sonrd
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger,static_wasm
      - -w -s

# ! ||--------------------------------------------------------------------------------||
# ! ||                                Tarball Archives                                ||
# ! ||--------------------------------------------------------------------------------||
universal_binaries:
  - id: sonrd-darwin-universal
    ids:
      - sonrd-darwin-amd64
      - sonrd-darwin-arm64
    replace: false
archives:
  - id: zipped
    builds:
      - sonrd-darwin-universal
      - sonrd-linux-amd64
      - sonrd-linux-arm64
      - sonrd-darwin-amd64
      - sonrd-darwin-arm64
    name_template: "{{.ProjectName}}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
  - id: binaries
    builds:
      - sonrd-darwin-universal
      - sonrd-linux-arm64
      - sonrd-linux-amd64
      - sonrd-darwin-amd64
      - sonrd-darwin-arm64
    name_template: "{{.ProjectName}}-{{ .Os }}-{{ .Arch }}"
    format: binary
checksum:
  name_template: "sha256sum.txt"
  algorithm: sha256

# ! ||--------------------------------------------------------------------------------||
# ! ||                              Release and Changelog                             ||
# ! ||--------------------------------------------------------------------------------||
release:
  github:
    owner: sonrhq
    name: core
  header: |
    ![Release Image](https://api.placid.app/u/cpqufnq7i?&commit[text]={{ .Commit }}&date[text]={{ .Date }}&version[text]={{ .Version }})

    < DESCRIPTION OF RELEASE >

    ## ⚡️ Binaries

    Binaries for Linux and Darwin (amd64 and arm64) are available below.
    Darwin users can also use the same universal binary `sonrd-{{ .Version }}-darwin-all` for both amd64 and arm64.

    ## 🔨 Build from source

    If you prefer to build from source, you can use the following commands:

    ````bash
    git clone https://github.com/sonrhq/core
    cd core && git checkout v{{ .Version }}
    make install
    # Then run sonrd
    sonrd version
    # v{{ .Version }}
    ````

    ## 🐳 Run with Docker

    As an alternative to installing and running sonrd on your system, you may run sonrd in a Docker container.
    The following Docker images are available in our registry:

    | Image Name                               | Base                                 | Description                       |
    |------------------------------------------|--------------------------------------|-----------------------------------|
    | `sonrhq/sonrd:{{ .Version }}`            | `distroless/static-debian11`         | Default image based on Distroless |
    | `sonrhq/sonrd:{{ .Version }}-standalone` | `distroless/static-debian11`         | Standalone testing node image     |
    | `sonrhq/sonr-faucet:{{ .Version }}`      | `distroless/static-debian11`         | Development environment faucet    |

    Example run:

    ```bash
    docker run sonrhq/sonrd:{{ .Version }} version
    # v{{ .Version }}
    ````

    All the images support `amd64` architectures.

  name_template: "Sonr Core - v{{.Version}} 🆔"
  mode: replace
  draft: false
changelog:
  skip: true
