version: 1
build:
  main: "cmd/sonrd"
accounts:
  - name: alice
    coins: ["2000000000snr", "200000000stake"]
  - name: bob
    coins: ["1000000000snr", "100000000stake"]
validators:
  - name: alice
    bonded: "100000000stake"
faucet:
  name: bob
  coins: ["50000000snr", "100000000stake"]
init:
  app:
    minimum-gas-prices: "0.025snr"
    api:
      enable: true
      swagger: true
  client:
    keyring-backend: "test"
