version: 1
build:
  main: cmd/sonrd
  binary: sonrd
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 2000000000snr
  - 200000000stake
- name: bob
  coins:
  - 1000000000snr
  - 100000000stake
faucet:
  name: bob
  coins:
  - 50000000snr
  - 100000000stake
  host: 0.0.0.0:4500
client:
  openapi:
    path: docs/static/blockchain.yaml
validators:
- name: alice
  bonded: 100000000stake
