version: "3"
networks:
  sonr-net:
services:
  node:
    image: sonrhq/sonrd:latest
    init: true
    container_name: validator
    networks:
      - sonr-net
    ports:
      - 1317:1317 # rest
      - 26656:26656 # p2p
      - 26657:26657 # rpc
      - 9090:9090 # grpc
      - 8080:8080 # highway
    restart: always
    environment:
      - SONR_LAUNCH_HIGHWAY_API_HOST
      - SONR_LAUNCH_HIGHWAY_API_PORT
      - SONR_LAUNCH_HIGHWAY_API_TIMEOUT
      - SONR_LAUNCH_HIGHWAY_DB_ICEFIREKV_HOST
      - SONR_LAUNCH_HIGHWAY_DB_ICEFIREKV_PORT
      - SONR_LAUNCH_HIGHWAY_DB_ICEFIRESQL_HOST
      - SONR_LAUNCH_HIGHWAY_DB_ICEFIRESQL_PORT
      - SONR_LAUNCH_HIGHWAY_SIGNING_KEY
  icefiredb:
    image: sonrhq/icefiredb:latest
    init: true
    container_name: icefiredb
    networks:
      - sonr-net
    ports:
      - 6001:6001
    restart: always
  icefiresql:
    image: sonrhq/icefiresql:latest
    init: true
    networks:
      - sonr-net
    ports:
      - 23306:23306
    restart: always
  faucet:
    image: sonrhq/sonr-faucet:latest
    init: true
    command: ["start", "http://validator:26657"]
    networks:
      - sonr-net
    depends_on:
      - node
    ports:
      - 4500:4500
    restart: always
