version: "3.7"
services:
  sonr-val-1:
    image: sonrhq/sonrd:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    command: flask run --host=
