version: "3"
networks:
  sonr-net: {}
services:
  node:
    init: true
    image: sonrhq/sonrd:latest
    command: sh entrypoint.sh
    ports:
      - 1317:1317 # rest
      - 26656:26656 # p2p
      - 26657:26657 # rpc
      - 9090:9090 # grpc
      - 8000:8080 # highway
    restart: always
