version: "3"
networks:
  sonr-net: {}
services:
  # Sonr Validator
  sonrd:
    init: true
    container_name: sonrd
    hostname: sonrd
    image: sonrhq/sonrd:latest
    command: ["sonrd", "start"]
    ports:
      - 1317:1317 # rest
      - 26657:26657 # rpc
      - 9090:9090 # grpc
    volumes:
      - ~/.sonr:/root/.sonr
    restart: always

  # Matrix Homeserver
  dendrite:
    init: true
    container_name: dendrite
    hostname: dendrite
    image: sonrhq/dendrite:latest
    ports:
      - 8008:8008 # rest
      - 8448:8448 # p2p

  # IPFS Gateway
  ipfs:
   container_name: ipfs
   hostname: ipfs
   image: sonrhq/ipfs:latest
