version: "3"
services:
  # Sonr Validator
  sonrd:
    init: true
    image: sonrd:latest
    entrypoint: ["sonrd", "start"]
    volumes:
      - /data/.sonr:/root/.sonr
    ports:
      - 1317:1317 # rest
      - 26657:26657 # rpc
      - 9090:9090 # grpc

  # Sonr Validator
  highway:
    init: true
    image: sonrd:latest
    entrypoint: ["sonrd", "serve"]
    ports:
      - 8000:8000 # api/htmx

  # IPFS node
  ipfs:
    image: ipfs/kubo:latest
    command: ["daemon"]
    ports:
      - 4001:4001 # swarm
      - 5001:5001 # api
      - 8080:8080 # gateway
