version: "3"

services:
  node:
    image: sonrhq/sonrd:latest
    init: true
    environment:
      - DOPPLER_TOKEN
    ports:
      - 1317:1317 # rest
      - 26656:26656 # p2p
      - 26657:26657 # rpc
      - 9090:9090 # grpc
      - 8080:8080 # highway
  # icefiredb:
  #   image: sonrhq/icefiredb:latest
  #   <<: *doppler-env
  #   ports:
  #     - 127.0.0.1:6001:6001
  # icefiresql:
  #   image: sonrhq/icefiresql:latest
  #   <<: *doppler-env
  #   ports:
  #     - 127.0.0.1:23357:23357
