version: "3"
services:
  # Sonr Validator
  sonrd:
    init: true
    container_name: sonrd
    image: sonrd:latest
    entrypoint: ["sh", "entrypoint.sh"]
    volumes:
      - $HOME/.sonr:/root/.sonr
    ports:
      - 1317:1317 # rest
      - 26657:26657 # rpc
      - 9090:9090 # grpc
    networks:
      - default

  # Sonr Validator
  highway:
    init: true
    image: sonrd:latest
    entrypoint: ["sonrd", "hway"]
    ports:
      - 8000:8000 # api/htmx
    networks:
      - default

  # IPFS node
  ipfs:
    image: ipfs/kubo:latest
    command: ["daemon"]
    ports:
      - 4001:4001 # swarm
      - 5001:5001 # api
      - 8080:8080 # gateway
    networks:
      - default

  # monolith:
  #   init: true
  #   image: matrixdotorg/dendrite-monolith:latest
  #   restart: always
  #   hostname: monolith
  #   container_name: monolith
  #   ports:
  #     - 8008:8008
  #     - 8448:8448
  #   volumes:
  #     - ./tmp/config:/etc/dendrite
  #     - ./tmp/dendrite_media:/var/dendrite/media
  #     - ./tmp/dendrite_jetstream:/var/dendrite/jetstream
  #     - ./tmp/dendrite_search_index:/var/dendrite/searchindex

networks:
  default:
