version: "3"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - arch=${ARCH:-x86_64}
    command: sh localnet.sh
    ports:
      - 1317:1317 # rest
      - 26656:26656 # p2p
      - 26657:26657 # rpc
      - 9090:9090 # grpc
      - 8080:8080 # highway
    environment:
      SONR_ICEFIRE_HOST: "icefirekv:6001"

  icefirekv:
    image: ghcr.io/sonrhq/icefirekv:latest
    ports:
      - 6001:6001 # icefiredb
      - 80:80 # icefiredb admin

  icefiresql:
    image: ghcr.io/sonrhq/icefiresql:latest
    ports:
      - 6002:6002 # icefiresql
      - 8081:8081 # icefiresql admin
