# fly.toml app configuration file generated for testnet-1 on 2023-12-31T15:58:36-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# ! ||--------------------------------------------------------------------------------||
# ! ||                                     Basics                                     ||
# ! ||--------------------------------------------------------------------------------||
app = "testnet-1"
primary_region = "iad"

[build]
  image = "sonrhq/sonrd:latest-standalone"

[deploy]
  strategy = "bluegreen"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[services.ports]]
  handlers = ["http"]
  port = 80
  force_https = true  # optional

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[services.ports]]
  handlers = ["http"]
  port = 80
  force_https = true  # optional

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[services.ports]]
  handlers = ["http"]
  port = 80
  force_https = true  # optional

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[services.ports]]
  handlers = ["http"]
  port = 80
  force_https = true  # optional

[[mounts]]
  source = "data"
  destination = "/data"
  processes = ["app"]

[[mounts]]
  source = "data"
  destination = "/data"
  processes = ["app"]

[[mounts]]
  source = "data"
  destination = "/data"
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
