version: "3"

tasks:
  proto:
    cmd: devbox -q run proto

  templ:
    cmd: templ generate

  build:vltd:
    cmd: go build -o /bin/vltd ./cmd/vltd/main.go

  build:sonrd:
    cmd: go build -o /bin/sonrd ./cmd/sonrd/main.go
