version: '3'
tasks:
  default:
    desc: List all tasks
    cmds:
      - task --list-all

  compose:up:
   desc: Start Local Network
   cmds:
    - earthly ./cmd+init --home $HOME/.sonr
    - docker compose -f ./docker-compose.yml up

  compose:down:
   desc: Stop Local Network
   cmds:
    - docker compose -f ./docker-compose.yml down

  devnet:deploy:
   desc: Docker Stack Deploy Devnet
   cmds:
    - ls

  devnet:update:
   desc: Update the Devnet deployment
   cmds:
    - ls

  testnet:deploy:
   desc: Docker Stack Deploy Testnet
   cmds:
    - ls

  testnet:update:
   desc: Update the Testnet Deployment
   cmds:
    - ls
