version: '3'

includes:
  deploy: ./build/Taskfile.yml

tasks:
  default:
   cmd: task --list-all
   silent: true

  init-matrix:
   dir: ./deploy/rails/dendrite
   cmds:
     - earthly --no-sat +init
