version: "3"
dotenv: [".env", "{{.ENV}}/.env.", "{{.HOME}}/.env"]
env:
  ENV: development
vars:
  VERSION:
    sh: echo $(git describe --tags --abbrev=0)
    default: "v0.0.0"
tasks:
  default:
    silent: true
    cmds:
      - echo ""
      - echo "⭐️ TASKFILE (sonrhq/core) ⭐️"
      - echo ""
      - task --list

  build:
    desc: Build the binary for the current platform
    cmds:
      - ignite chain build

  chain:
    desc: Serve the blockchain locally with verbose logging
    cmds:
      - ignite chain serve --reset-once -v

  chain:docker:
    desc: Serve the blockchain locally with verbose logging
    cmds:
      - docker compose up --abort-on-container-exit --build

  chain:slow-start:
    desc: Serve the blockchain locally with verbose logging
    cmds:
      - ignite chain serve --reset-once -v

  generate:
    desc: Generate the protobuf files
    cmds:
      - ignite generate proto-go -y

  db:
    desc: Run the database locally
    dir: ./.tmp/bin
    cmds:
      - ./icefire start

  db:install:
    desc: Install the database locally
    dir: ./.tmp
    cmds:
      - git clone https://github.com/sonrhq/IceFireDB.git IceFireDB
      - make -C ./IceFireDB
      - mv ./IceFireDB/bin/icefire ./bin/icefire
      - rm -rf ./IceFireDB

  deps:
    desc: Install the dependencies
    cmds:
      - mkdir -p ./.tmp/bin
      - task: db:install
      - npm i concurrently -g
      - curl https://get.ignite.com/cli! | bash

  start:
    desc: Start the Blockchain and Database locally
    cmds:
        - conc "task db" "task chain" -n "db,chain" -g -r
