version: '3'
tasks:
  default:
    cmds:
      - task --list-all

  tidy:
    cmds:
      - earthly --no-sat +deps

  build:
    cmds:
      - earthly --sat=david +build

  builder:
    cmds:
      - earthly sat wake goliath
      - earthly --sat=goliath +builder

  push:
    deps:
      - build
    cmds:
      - gum confirm "Push to Docker Hub?" && docker push sonrhq/faucet:latest && docker push sonrhq/vmbase:latest && docker push sonrhq/sonrd:latest
