version: "3"
dotenv:
  - .env
  - .env.rails

includes:
  build: ./.tasks/Build.yml
  deploy: ./.tasks/Deploy.yml
  dev: ./.tasks/Dev.yml
  gen: ./.tasks/Gen.yml
  release: ./.tasks/Release.yml
  test: ./.tasks/Test.yml

tasks:
  generate:
    desc: "Generate Templ and Proto files"
    cmds:
      - task: gen:proto
      - task: gen:proto-doc
      - task: gen:templ

  test-essential:
    desc: "Run essential tests"
    cmds:
      - task: test

  lint:
    desc: "Run linters"
    cmds:
      - task: trunk fmt --all

  compose-up:
    dir: ./docker
    cmds:
      - task: compose-down
      - templ generate
      - task: build:current
      - task: build:dockerfile
      - docker compose up --abort-on-container-exit

  compose-down:
    dir: ./docker
    ignore_error: true
    cmds:
      - docker compose down
