version: '3'
tasks:
  default:
    cmds:
      - task --list-all

  init:
    cmds:
      - earthly --no-sat +setup

  build:
    deps:
      - init
    cmds:
      - earthly sat wake builder
      - earthly --sat=builder --org=sonrhq ./chain+build
      - earthly --sat=builder --org=sonrhq ./rails+build

  tests:
    deps:
     - init
    cmds:
     - earthly sat wake tester
     - earthly --sat=tester --org=sonrhq ./identity+test
     - earthly --sat=tester --org=sonrhq ./service+test
     - earthly --sat=tester --org=sonrhq ./chain+test

  lint:
   deps:
    - init
   cmds:
    - earthly sat wake linter
    - earthly --sat=linter --org=sonrhq ./identity+lint
    - earthly --sat=linter --org=sonrhq ./service+lint
