version: '3'

includes:
  deploy: ./deploy/Taskfile.yml
  proto: ./proto/Taskfile.yml

tasks:
  default:
   cmd: task --list-all
   silent: true

  install:
    cmds:
      - go install github.com/cosmtrek/air@latest
      - brew install tmux

  build:
   aliases:
     - "b"
   cmds:
    - rm -rf bin/ && mkdir ./bin/
    - templ generate
    - goreleaser build --single-target --clean --snapshot -o ./bin/sonrd
    - rm -rf dist

  build-docker:
    aliases:
      - "bd"
    cmds:
      - earthly +docker
      - mv ./cmd/studio/build/bin ./bin

  build-studio:
    aliases:
      - "bs"
    cmds:
      - earthly +studio
      - mv ./cmd/studio/build/bin ./bin

  generate:
   aliases:
      - "gen"
      - "g"
   cmds:
    - earthly --no-sat +generate
    - task: proto:gogo-gen
    - rm -rf sonr
    - cp -R -v ./github.com/sonrhq/sonr/x/* ./x
    - rm -rf github.com
    - go mod tidy

  dev-api:
   aliases:
     - "dxa"
   cmds:
   - task: deploy:local-gateway

  dev-node:
   aliases:
     - "dxn"
   cmds:
     - task: deploy:local-node
