version: "3"

includes:
  web:dashboard:
    taskfile: ./web/dashboard/Taskfile.yaml
    dir: web/dashboard
  web:wallet:
    taskfile: ./web/wallet/Taskfile.yaml
    dir: web/wallet

tasks:
  bind:
    cmds:
      - echo "Setting up Gomobile..."
      - go install golang.org/x/mobile/cmd/gomobile@latest
      - go mod download golang.org/x/mobile
      - gomobile init
      - task: bind:ios
      - task: bind:android

  bind:android:
    cmds:
      - echo "Building Sonr Motor Node (Android)"
      - gomobile bind -ldflags='-s -w' -target=android -o .../dist/io.sonr.motor.aar

  bind:ios:
    cmds:
      - echo "Building Sonr Motor Node (iOS)"
      - gomobile bind -ldflags='-s -w' -bundleid=io.sonr.motor -target=ios -o SonrMotor.xcframework

  build:
    cmds:
      - task: build:buf:core
      - task: build:buf:blockchain
      - task: build:cli
      - task: build:swagger
      - task: build:chain

  build:chain:
    summary: Build the project for production without release mode
    cmds:
      - starport chain build
    silent: true

  build:cli:
    dir: cmd/highway-cli
    cmds:
      - echo "Building Sonr Highway CLI"
      - go build -o highway-cli main.go

  build:swagger:
    cmds:
      - echo "Building swagger api docs for highway"
      - swag i -g pkg/highway/server.go --output docs/highway
      - echo "Building Open api docs for Blockchain"
      - starport generate openapi
      - starport generate proto-go
      - go mod tidy

  build:buf:
    cmds:
      - echo "Building Protobufs and pushing to registry"
      - task: build:buf:core
      - task: build:buf:blockchain

  build:buf:core:
    dir: proto
    cmds:
      - echo "Generating and Pushing Protobufs for Highway, Motor, and Host"
      - buf mod update
      - buf build
      - buf push

  build:buf:blockchain:
    dir: internal/blockchain/proto
    cmds:
      - echo "Generating and Pushing Protobufs for Blockchain Modules"
      - buf mod update
      - buf build
      - buf push

  deploy:docs:
    dir: docs
    cmds:
      - echo "Deploying docs to gh-pages"
      - USE_SSH=true yarn deploy

  gen:proto:
    cmds:
      - echo "Generating Protobufs"
      - ignite generate proto-go
      - ignite generate openapi
      - go mod tidy

  serve:chain:
    summary: Serve the blockchain using starport
    cmds:
      - ignite chain serve --reset-once
    silent: true

  serve:docs:
    summary: Serve the documentation using starport
    cmds:
      - task: docs:serve
    silent: true

  start:chain:
    summary: Start a locally built blockchain daemon
    deps: [build-chain]
    cmds:
      - rm -rf ~/.sonr
      - sonrd init my-node --chain-id sonr
      - sonrd keys add --keyring-backend test alice --home ~/.sonr
      - sonrd add-genesis-account $(sonrd keys show alice -a) 1000000000000000stake,1000000000000snr
      - sonrd gentx alice 1000000000000000stake --chain-id sonr
      - sonrd collect-gentxs
      - sonrd start

  start:docs:
    summary: Start the documentation server
    cmds:
      - task: docs:start

  release:web:
    summary: Build the web dashboard for release
    cmds:
      # - task: web:dashboard:build
      - task: web:wallet:build


  docs:
    cmds:
      - echo "yarn docusaurus..."
      - yarn docusaurus
    silent: true
    dir: docs

  docs:start:
    cmds:
      - echo "yarn start..."
      - yarn start
    silent: true
    dir: docs

  docs:build:
    cmds:
      - echo "yarn build..."
      - yarn build
    silent: true
    dir: docs

  docs:swizzle:
    cmds:
      - echo "yarn swizzle..."
      - yarn swizzle
    silent: true
    dir: docs

  docs:deploy:
    cmds:
      - echo "yarn deploy..."
      - USE_SSH=true yarn deploy
    silent: true
    dir: docs

  docs:clear:
    cmds:
      - echo "yarn clear..."
      - yarn clear
    silent: true
    dir: docs

  docs:serve:
    cmds:
      - echo "yarn serve..."
      - yarn serve
    silent: true
    dir: docs
