version: '3'
tasks:
  default:
    cmds:
      - bob clone --https

  build:
    cmds:
      - earthly +build
      - earthly +vmbase

  push:
    deps:
      - build
    cmds:
      - gum confirm "Push to Docker Hub?" && docker push sonrhq/faucet:latest && docker push sonrhq/vmbase:latest && docker push sonrhq/sonrd:latest
