version: '3'

includes:
  deploy: ./build/Taskfile.yml

tasks:
  default:
   cmd: task --list-all
   silent: true

  init-matrix:
   dir: ./deploy/rails/dendrite
   cmds:
     - earthly --no-sat +init

  build:
   cmds:
    - rm -rf bin/ && mkdir ./bin/
    - goreleaser build --single-target --clean --snapshot -o ./bin/sonrd
    - rm -rf dist

  generate:
   cmds:
    - earthly --no-sat +templates

  serve:
   cmds:
    - go install github.com/cosmtrek/air@latest
    - air -c ./build/dev/air-gateway.toml

  start:
   cmds:
    - air -c ./build/dev/air-node.toml
