version: "3"
dotenv:
  - .env
  - .env.rails

includes:
  build: ./.taskfiles/Build.yml
  deploy: ./.taskfiles/Deploy.yml
  dev: ./.taskfiles/Dev.yml
  gen: ./.taskfiles/Gen.yml
  release: ./.taskfiles/Release.yml
  test: ./.taskfiles/Test.yml

tasks:
  generate:
    desc: "Generate Templ and Proto files"
    cmds:
      - task: gen:proto
      - task: gen:proto-doc
      - task: gen:templ

  test-essential:
    desc: "Run essential tests"
    cmds:
      - task: test

  compose-up:
    cmds:
      - task: compose-down
      - templ generate
      - task: build:current
      - docker compose -f ./deploy/testnet/docker-compose.dev.yml up --abort-on-container-exit

  compose-down:
    ignore_error: true
    cmds:
      - docker compose -f ./deploy/testnet/docker-compose.dev.yml down
