version: "3"

includes:
  build: ./tasks/Build.yml
  deploy: ./tasks/Deploy.yml
  dev: ./tasks/Dev.yml
  gen: ./tasks/Gen.yml
  test: ./tasks/Test.yml

tasks:
  generate:
    desc: "Generate Templ and Proto files"
    cmds:
      - task: gen:proto
      - task: gen:proto-doc
      - task: gen:templ

  test-essential:
    desc: "Run essential tests"
    cmds:
      - task: test

  lint:
    desc: "Run linters"
    cmds:
      - task: trunk fmt --all

  compose-up:
    cmds:
      - task: compose-down
      - templ generate
      - task: build:current
      - task: build:dockerfile
      - docker compose up --abort-on-container-exit

  compose-down:
    ignore_error: true
    cmds:
      - docker compose down
