version: "3"
dotenv:
  - .env

tasks:
  grpcui:
    desc: "Launch grpcui for the node"
    cmds:
      - go install github.com/fullstorydev/grpcui/cmd/grpcui@latest
      - grpcui -plaintext localhost:9090

  testnet:
    desc: "Launch a testnet"
    cmds:
      - make sh-testnet

  testnet:ibc:
    desc: "Launch a testnet with IBC enabled"
    cmds:
      - make testnet

  docker:
    desc: "Build and run the docker container"
    cmds:
      - make local-image

  proto:
    aliases:
      - "gen"
    desc: "Generate the protobuf files"
    cmds:
      - make proto-gen

  hway:run:
    desc: "Run the hway"
    cmds:
      - task: templ
      - go run ./cmd/hway/main.go

  hway:build:
    desc: "Build the hway"
    cmds:
      - task: templ
      - go build -o bin/hway ./cmd/hway/main.go

  hway:release:
    desc: "Build the hway"
    cmds:
      - goreleaser release --clean

  templ:
    desc: "Generate all templ files (https://templ.guide)"
    cmds:
      - go install github.com/a-h/templ/cmd/templ@latest
      - templ generate
