version: "3"
dotenv: [".env", "{{.ENV}}/.env.", "{{.HOME}}/.env"]

vars:
  CGO_ENABLED: 1
  WASMVM_URL: https://github.com/CosmWasm/wasmvm/releases/download
  VERSION:
    sh: echo $(git describe --tags --abbrev=0)
    default: v0.0.0
  COMMIT:
    sh: git log -n 1 --format=%h
    default: 0000000
  DATE:
    sh: date -u '+%m/%d/%y %I:%M:%S%p'
    default: "1970-01-01_00:00:00AM"
  COSMWASM_VERSION:
    sh: go list -m github.com/CosmWasm/wasmvm | sed 's/.* //'
    default: v1.3.0
  GO_VERSION:
    sh: cat go.mod | grep -E 'go [0-9].[0-9]+' | cut -d ' ' -f 2
    default: 1.21
  GITHUB_TOKEN:
    sh: echo $GITHUB_TOKEN
    default: ""
  GORELEASER_IMAGE: ghcr.io/goreleaser/goreleaser-cross:v{{.GO_VERSION}}
tasks:
  # ----------------------------------------------------------------------------
  # -- Run Tasks ---------------------------------------------------------------
  # ----------------------------------------------------------------------------
  default:
    desc: Print the version
    silent: true
    cmds:
      - task -l

  build:
    desc: Build the binary for all platforms
    cmds:
      - make build

  docker-release:
    desc: Build the binary for docker
    cmds:
      - task: docker-build
      - for: ["ghcr.io/sonr-io", "registry.digitalocean.com/sonrhq"]
        task: docker-push
        vars:
          REGISTRY: '{{.ITEM}}'
          IMAGE: sonrd

  docker-build:
    silent: true
    desc: Build, tag and push the docker image
    cmds:
      - docker build -f ./Dockerfile . -t sonrd

  docker-tag:
    silent: true
    internal: true
    desc: Build, tag and push the docker image
    cmds:
      - echo "Tagging {{.IMAGE}} with {{.REGISTRY}}/{{.IMAGE}}"
      - docker tag sonrd {{.REGISTRY}}/{{.IMAGE}}:{{.VERSION}}
      - docker tag sonrd {{.REGISTRY}}/{{.IMAGE}}:{{.COMMIT}}
    requires:
      vars: [IMAGE, REGISTRY]

  docker-push:
    silent: true
    internal: true
    desc: Build, tag and push the docker image
    cmds:
      - echo "Pushing {{.REGISTRY}}/{{.IMAGE}}..."
      - docker push {{.REGISTRY}}/{{.IMAGE}} --all-tags
    requires:
      vars: [IMAGE, REGISTRY]
  # ----------------------------------------------------------------------------
  # -- Protobuf Tasks -------------------------------------------------------------
  # ----------------------------------------------------------------------------
  buf-mod:
    dir: proto
    internal: true
    silent: true
    desc: Update the buf.lock file
    cmds:
      - buf mod update

  buf-build:
    dir: proto
    internal: true
    silent: true
    desc: Build the protobuf files
    deps: [buf-mod]
    cmds:
      - buf build

  buf-push:
    dir: proto
    internal: true
    silent: true
    desc: Push the protobuf files to the registry
    deps: [buf-build]
    cmds:
      - buf push

  generate:
    aliases:
      - gen
    desc: Generate the protobuf files
    cmds:
      - |
        make proto-all

  go-cross-build:
    desc: Build the binary for all platforms
    cmds:
      - |
        docker run \
        --rm \
        -e COSMWASM_VERSION={{.COSMWASM_VERSION}} \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v `pwd`:/go/src/sonrd \
        -w /go/src/sonrd \
        {{.GORELEASER_IMAGE}} \
        build \
        --clean \
        --skip=validate \
        --id={{.ID}} \
    requires:
      vars: [ID]
