version: "3"
dotenv: [".env", "{{.ENV}}/.env.", "{{.HOME}}/.env"]
env:
  ENV: development
vars:
  VERSION:
    sh: echo $(git describe --tags --abbrev=0)
    default: "v0.0.0"
tasks:
  default:
    aliases:
      - "help"
    silent: true
    cmds:
      - echo ""
      - echo "⭐️ TASKFILE (sonrhq/core) ⭐️"
      - echo ""
      - task --list

  chain:
    desc: Serve the blockchain locally with verbose logging
    aliases:
      - "srv"
    summary: |
      Serve Blockchain Locally

      This task will serve the blockchain locally. It will also reset the blockchain
    cmds:
      - ignite chain serve --clear-cache --reset-once -v
    interactive: true

  generate:
    aliases:
      - "gen"
    dir: scripts
    desc: Generate the protobuf files
    summary: |
      Generate Protobuf Files

      This task will generate the protobuf files
    cmds:
      - ignite generate proto-go

  docker:build:
    desc: Build the docker image
    summary: |
      Build Docker Image

      This task will build the docker image
    cmds:
      - docker build -t sonr .
      - docker tag sonr ghcr.io/sonrhq/sonrd:latest
      - docker tag sonr ghcr.io/sonrhq/sonrd:{{.VERSION}}

  docker:push:
    aliases:
      - "docker"
    desc: Push the docker image
    summary: |
      Push Docker Image

      This task will push the docker image
    cmds:
      - docker push ghcr.io/sonrhq/sonrd:latest
      - docker push ghcr.io/sonrhq/sonrd:{{.VERSION}}
    deps:
      - docker:build
