version: '3'
tasks:
  default:
    cmds:
      - task --list-all

  build:
    cmds:
      - earthly sat wake tester
      - earthly --sat=tester --org=sonrhq ./chain+docker
      - earthly --sat=tester --org=sonrhq ./rails+ipfs
      - earthly --sat=tester --org=sonrhq ./rails+postgres

  tests:
    cmds:
     - earthly sat wake tester
     - earthly --sat=tester --org=sonrhq ./identity+test
     - earthly --sat=tester --org=sonrhq ./service+test
     - earthly --sat=tester --org=sonrhq ./chain+test

  lint:
   cmds:
    - earthly sat wake linter
    - earthly --sat=linter --org=sonrhq ./identity+lint
    - earthly --sat=linter --org=sonrhq ./service+lint

  publish:
    cmds:
      - earthly sat wake builder
      - earthly --sat=builder --push --org=sonrhq ./chain+docker
      - earthly --sat=builder --push --org=sonrhq ./chain+runner
      - earthly --sat=tester --push --org=sonrhq ./rails+ipfs
      - earthly --sat=tester --push --org=sonrhq ./rails+postgres
