version: "3"
dotenv: [".env", "{{.ENV}}/.env.", "{{.HOME}}/.env"]
includes:
  docker:
    taskfile: ./build/Taskfile.yml
    dir: .
  proto:
    taskfile: ./proto/Taskfile.yml
    dir: ./proto
vars:
  CGO_ENABLED: 1
  WASMVM_URL: https://github.com/CosmWasm/wasmvm/releases/download
  VERSION:
    sh: echo $(git describe --tags --abbrev=0)
    default: v0.0.0
  COMMIT:
    sh: git log -n 1 --format=%h
    default: 0000000
  DATE:
    sh: date -u '+%m/%d/%y %I:%M:%S%p'
    default: "1970-01-01_00:00:00AM"
  COSMWASM_VERSION:
    sh: go list -m github.com/CosmWasm/wasmvm | sed 's/.* //'
    default: v1.3.0
  GO_VERSION:
    sh: cat go.mod | grep -E 'go [0-9].[0-9]+' | cut -d ' ' -f 2
    default: 1.21
  GITHUB_TOKEN:
    sh: echo $GITHUB_TOKEN
    default: ""
  GORELEASER_IMAGE: ghcr.io/goreleaser/goreleaser-cross:v{{.GO_VERSION}}
  # ----------------------------------------------------------------------------
  # -- Run Tasks ---------------------------------------------------------------
  # ----------------------------------------------------------------------------
tasks:
  default:
    desc: Print the version
    silent: true
    cmds:
      - task -l

  build:
    aliases:
      - b
    desc: Build the binary for current platform
    cmds:
      - make build

  build-all:
    aliases:
      - ba
    desc: Build the binary for all platforms and docker
    cmds:
      - make build
      - task: docker:build

  generate:
    aliases:
      - gen
    desc: Generate the protobuf files
    cmds:
      - |
        make proto-all
