version: '3'

includes:
  deploy: ./deploy/Taskfile.yml

tasks:
  default:
   cmd: task --list-all
   silent: true

  install:
    cmds:
      - go install github.com/cosmtrek/air@latest
      - brew install tmux

  build:
   aliases:
     - "b"
   cmds:
    - rm -rf bin/ && mkdir ./bin/
    - templ generate
    - goreleaser build --single-target --clean --snapshot -o ./bin/sonrd
    - rm -rf dist

  generate:
   aliases:
      - "gen"
      - "g"
   cmds:
    - earthly --no-sat +generate
    - earthly --no-sat +templates
    - go mod tidy

  dev:gateway:
   aliases:
     - "devg"
     - "dg"
   cmds:
    - air -c ./deploy/local/air-gateway.toml

  dev:node:
   aliases:
     - "devn"
     - "dn"
   cmds:
    - air -c ./deploy/local/air-node.toml

  dev:
   aliases:
     - "d"
   cmd: tmux new-session -d 'task dev:node' \; split-window -h 'task dev:gateway' \; attach

  grpcui:
   cmd: grpcui -plaintext localhost:9090
