version: "3"

includes:
  deploy: ./tasks/Deploy.yml
  dev: ./tasks/Dev.yml
  gen: ./tasks/Gen.yml
  test: ./tasks/Test.yml

tasks:
  build:
    desc: "Builds the project for current platform"
    cmds:
      - rm -rf bin/ && mkdir ./bin/
      - goreleaser build --id=sonrd --single-target --clean --snapshot -o ./bin/sonrd
      - rm -rf dist

  build-ci:
    desc: "Builds the project for all platforms"
    cmds:
      - go
      - goreleaser build --id=sonrd --single-target --clean --snapshot

  generate:
    desc: "Generate Templ and Proto files"
    cmds:
      - task: gen:proto
      - task: gen:swagger
      - task: gen:templ

  dev-up:
    cmds:
      - tmux new-session -d -s dev 'task dev:node'
      - tmux split-window -h 'task dev:gateway'
      - tmux -2 attach-session -d

  dev-down:
    ignore_error: true
    cmds:
      - tmux kill-session -t dev

  test-essential:
    desc: "Run essential tests"
    cmds:
      - task: test
