version: "3"
dotenv:
  - .env

includes:
  docker: .taskfiles/Docker.yml
  deploy: .taskfiles/Deploy.yml
  gen: .taskfiles/Gen.yml
  release: .taskfiles/Release.yml
  test: .taskfiles/Test.yml

tasks:
  install:
    desc: "Setup the development environment"
    cmds:
      - go install github.com/cosmtrek/air@latest
      - go install github.com/kollalabs/protoc-gen-openapi@latest
      - go install cosmossdk.io/orm/cmd/protoc-gen-go-cosmos-orm@latest
      - go install cosmossdk.io/orm/cmd/protoc-gen-go-cosmos-orm-proto@latest
      - go install github.com/a-h/templ/cmd/templ@latest
      - go install github.com/go-task/task/v3/cmd/task@latest

  dev:
    desc: "Start development server"
    cmds:
      - task: build
      - air -c ./deploy/air.toml

  build:
    desc: "Build the project"
    cmds:
      - task: gen:prisma
      - task: docker:sonrd
      - task: docker:hway

  generate:
    desc: "Generate Templ and Proto files"
    cmds:
      - task: gen:proto
      - task: gen:proto-doc
      - task: gen:templ

  test-essential:
    desc: "Run essential tests"
    cmds:
      - task: test

  release-gcp:
    desc: "Release the docker images"
    cmds:
      - task: build
