version: 1
build:
  main: cmd/sonrd
  binary: sonrd
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: validator
  coins:
  - 20000snr
  - 100000000stake
  mnemonic: satisfy adjust timber high purchase tuition stool faith fine install that
    you unaware feed domain license impose boss human eager hat rent enjoy dawn
- name: alice
  coins:
  - 20000snr
  - 200000000stake
  mnemonic: notice oak worry limit wrap speak medal online prefer cluster roof addict
    wrist behave treat actual wasp year salad speed social layer crew genius
- name: bob
  coins:
  - 20000snr
  - 200000000stake
faucet:
  name: bob
  coins:
  - 50000000snr
  - 100000000stake
  host: 0.0.0.0:4500
client:
  openapi:
    path: docs/static/blockchain.yaml
validators:
- name: validator
  bonded: 70000000stake
