accounts:
  - mnemonic: "satisfy adjust timber high purchase tuition stool faith fine install that you unaware feed domain license impose boss human eager hat rent enjoy dawn"
    name: validator
    coins: ["200000snr", "100000000stake"]
    # address: snr1phaxpevm5wecex2jyaqty2a4v02qj7qmqe4lvm
  - mnemonic: "notice oak worry limit wrap speak medal online prefer cluster roof addict wrist behave treat actual wasp year salad speed social layer crew genius"
    name: test1
    coins: ["200000snr", "200000000stake"]
    # address: snr1cyyzpxplxdzkeea7kwsydadg87357qnaglp5wk
validator:
  name: validator
  staked: "70000000stake"
client:
  openapi:
    path: "docs/static/blockchain.yaml"
faucet:
  name: test1
  coins: ["50000000snr", "100000000stake"]
build:
  main: "cmd/sonrd"
  binary: "sonrd"
