version: "3"
networks:
  sonr-net: {}
services:
  # Sonr Validator
  sonrd:
    init: true
    container_name: sonrd
    hostname: sonrd
    image: sonrd-runner:latest
    command: ["start"]
    ports:
      - 1317:1317 # rest
      - 26657:26657 # rpc
      - 9090:9090 # grpc
    restart: always

  # Matrix Homeserver
  dendrite:
    init: true
    container_name: dendrite
    hostname: dendrite
    image: dendrite-runner:latest
    ports:
      - 8008:8008 # rest
      - 8448:8448 # p2p

  # IPFS Gateway
  ipfs:
   container_name: ipfs
   hostname: ipfs
   image: ipfs-runner:latest
   ports:
     - 4001:4001 # rest
     - 5001:5001 # p2p
     - 8080:8080 # gateway

  # Sonr Faucet
  faucet:
   container_name: faucet
   hostname: faucet
   image: faucet-runner:latest
   ports:
     - 3000:3000 # rest

  # Cloudflared Reverse Proxy
  reverse-proxy:
   image: cloudflared-runner:latest
   depends_on:
     - ipfs
     - faucet
     - dendrite
     - sonrd
   expose:
     - 80
     - 443
     - 8080
