version: "3"

tasks:
  default:
    desc: "Builds the project for current platform"
    cmds:
      - templ generate
      - rm -rf bin/ && mkdir ./bin/
      - go build -o ./bin/sonrd ./cmd/sonrd
      - rm -rf dist

  current:
    desc: "Builds the project for current platform"
    cmds:
      - goreleaser build --snapshot --rm-dist --single-target -o ./bin/sonrd

  dockerfile:
    desc: "Builds the project for current platform"
    cmds:
      - docker build -t sonrd:latest -f ./Dockerfile .

  ipfs:
    dir: deploy
    cmds:
      - earthly +ipfs --domain=ipfs.sonr.dev

  faucet:
    internal: true
    dir: _workers/faucet-testnet
    cmds:
      - earthly +build

  highway:
    internal: true
    dir: _workers/highway-proxy
    cmds:
      - earthly +build

  workers:
    cmds:
      - task: cosmscan
      - task: faucet
      - task: highway

  devcontainer:
    desc: "Builds the project for current platform"
    cmds:
      - docker run -it --rm
        -v ./tmp/envbuilder:/workspaces
        -e GIT_URL=https://github.com/sonrhq/sonr
        -e INIT_SCRIPT=zsh
        ghcr.io/coder/envbuilder
