version: "3"

tasks:
  default:
    desc: "Builds the project for current platform"
    cmds:
      - templ generate
      - rm -rf bin/ && mkdir ./bin/
      - goreleaser build --single-target --clean --snapshot -o ./bin/sonrd
      - rm -rf dist

  ipfs:
    dir: deploy
    cmds:
      - earthly +ipfs --domain=ipfs.sonr.dev

  matrix:
    dir: deploy
    cmds:
      - earthly +matrix --domain=matrix.sonr.dev

  cosmscan:
    internal: true
    dir: _workers/cosmscan-indexer
    cmds:
      - earthly +build

  faucet:
    internal: true
    dir: _workers/faucet-testnet
    cmds:
      - earthly +build

  highway:
    internal: true
    dir: _workers/highway-proxy
    cmds:
      - earthly +build

  workers:
    cmds:
      - task: cosmscan
      - task: faucet
      - task: highway
