version: "3"

tasks:
  plan:
    desc: "Plan the infrastructure"
    dir: ./deploy
    cmds:
      - terraform init
      - terraform plan

  apply:
    desc: "Apply the infrastructure"
    dir: ./deploy
    cmds:
      - terraform init
      - terraform apply -auto-approve

  destroy:
    desc: "Destroy the infrastructure"
    dir: ./deploy
    cmds:
      - terraform init
      - terraform destroy -auto-approve

  workers:
    desc: "Deploy Cloudflare workers"
    cmds:
      - task: workers-cosmscan
      - task: workers-highway
      - task: workers-faucet

  workers-cosmscan:
    internal: true
    dir: _workers/cosmscan-indexer
    cmds:
      - earthly +deploy

  workers-highway:
    internal: true
    dir: _workers/faucet-testnet
    cmds:
      - earthly +deploy

  workers-faucet:
    internal: true
    dir: _workers/faucet-testnet
    cmds:
      - earthly +deploy

  pack:
    dir: ./deploy
    cmds:
      - packer build base.pkr.hcl
