version: "3"

tasks:
  setup:
    desc: "Setup the development environment"
    cmds:
      - go install github.com/cosmtrek/air@latest
      - go install github.com/kollalabs/protoc-gen-openapi@latest
      - go install cosmossdk.io/orm/cmd/protoc-gen-go-cosmos-orm@latest
      - go install cosmossdk.io/orm/cmd/protoc-gen-go-cosmos-orm-proto@latest
      - go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - go install github.com/a-h/templ/cmd/templ@latest
      - brew install tmux
      - brew install earthly
      - brew install buf
      - brew tap tinygo-org/tools
      - brew install tinygo

  default:
    cmd: air -c ./networks/local/air.toml

  cosmscan:
    desc: "Run the CosmScan indexer with Wrangler"
    dir: _workers/cosmscan-indexer
    cmd: earthly +dev

  highway:
    desc: "Run the Highway worker with Wrangler"
    cmd: earthly +dev

  faucet:
    desc: "Run the Faucet worker with Wrangler"
    dir: _workers/faucet-testnet
    cmd: earthly +dev
