root = "."
tmp_dir = "tmp"

[build]
  bin = "./bin/sonrd"
  cmd = "templ generate && task build"
  delay = 1000
  exclude_dir = ["static", "tmp", "vendor", "scripts", ".github", ".vscode","cmd", "app/highway", "pkg/nebula", "bind", "build", "dist"]
  exclude_file = []
  exclude_regex = [".*_templ.go", "*.templ", "*.md"]
  exclude_unchanged = true
  follow_symlink = false
  full_bin = "sh ./networks/local/entrypoint.sh"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html"]
  kill_delay = "0s"
  log = ".tmp/build-errors.log"
  send_interrupt = false
  stop_on_error = false

[color]
  app = "blue"
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true
