version: "3"
vars:
  CGO_ENABLED: 1
  WASMVM_URL: https://github.com/CosmWasm/wasmvm/releases/download
  VERSION:
    sh: echo $(git describe --tags --abbrev=0)
    default: v0.0.0
  COMMIT:
    sh: git log -n 1 --format=%h
    default: 0000000
  DATE:
    sh: date -u '+%m/%d/%y %I:%M:%S%p'
    default: "1970-01-01_00:00:00AM"
  COSMWASM_VERSION:
    sh: go list -m github.com/CosmWasm/wasmvm | sed 's/.* //'
    default: v1.3.0
  GO_VERSION:
    sh: cat go.mod | grep -E 'go [0-9].[0-9]+' | cut -d ' ' -f 2
    default: 1.21
  GITHUB_TOKEN:
    sh: echo $GITHUB_TOKEN
    default: ""
  GORELEASER_IMAGE: ghcr.io/goreleaser/goreleaser-cross:v{{.GO_VERSION}}
tasks:
  # ----------------------------------------------------------------------------
  # -- Run Tasks ---------------------------------------------------------------
  # ----------------------------------------------------------------------------
  default:
    desc: Print the version
    silent: true
    cmds:
      - task -l

  release:
    desc: Build the binary for docker
    cmds:
      - task: docker-build
      - for: ["ghcr.io/sonr-io", "registry.digitalocean.com/sonrhq"]
        task: docker-push
        vars:
          REGISTRY: '{{.ITEM}}'
          IMAGE: sonrd

  build:
    silent: true
    desc: Build, tag and push the docker image
    cmds:
      - docker build -f ./docker/deploy/Dockerfile . -t sonrd

  start:
    silent: true
    desc: Start the docker image
    dir: ./docker/start
    cmds:
      - docker compose up
    deps:
      - build

  tag:
    silent: true
    desc: Build, tag and push the docker image
    cmds:
      - echo "Tagging {{.IMAGE}} with {{.REGISTRY}}/{{.IMAGE}}"
      - docker tag sonrd {{.REGISTRY}}/{{.IMAGE}}:{{.VERSION}}
      - docker tag sonrd {{.REGISTRY}}/{{.IMAGE}}:{{.COMMIT}}
    requires:
      vars: [IMAGE, REGISTRY]

  push:
    silent: true
    desc: Build, tag and push the docker image
    cmds:
      - echo "Pushing {{.REGISTRY}}/{{.IMAGE}}..."
      - docker push {{.REGISTRY}}/{{.IMAGE}} --all-tags
    requires:
      vars: [IMAGE, REGISTRY]
