version: "3"
dir: ../
# -----------------------------------------------------------------------------
# -- Project Config ------------------------------------------------------------
# -----------------------------------------------------------------------------
vars:
  VERSION:
    sh: echo $(git describe --tags --abbrev=0)
    default: "v0.0.0"
  COMMIT:
    sh: git log -n 1 --format=%h
    default: "0000000"
  DATE:
    sh: date -u '+%m/%d/%y %I:%M:%S%p'
    default: "1970-01-01_00:00:00AM"
  REGISTRY: ghcr.io/sonrhq

# ----------------------------------------------------------------------------
# -- Public Tasks ------------------------------------------------------------
# ----------------------------------------------------------------------------
tasks:
  default:
    desc: Build the binary for mac, linux
    cmds:
      - task: go-build
        vars:
          OS: linux
          ARCH: amd64
      - task: go-build
        vars:
          OS: linux
          ARCH: arm64
      - task: go-build
        vars:
          OS: darwin
          ARCH: amd64

  release:
    desc: Build the binary for docker
    cmds:
      - task: docker-release
        vars:
          IMAGE: sonr-base
      - task: docker-release
        vars:
          IMAGE: sonr-node

  release:testnet:
    desc: Build the binary for docker
    cmds:
      - task: release:vals
      - task: release:sentrys
      - task: release:nodes
      - task: release:deps

  release:nodes:
    internal: true
    desc: Release node docker images
    cmds:
      - task: docker-release-node
        vars:
          TOKEN: $DOPPLER_NDE_AUSTIN_TOKEN
          MONIKER: austin

  release:vals:
    internal: true
    desc: Release validator docker images
    cmds:
      - task: docker-release-val
        vars:
          TOKEN: $DOPPLER_VAL_BROOKLYN_TOKEN
          MONIKER: brooklyn
      - task: docker-release-val
        vars:
          TOKEN: $DOPPLER_VAL_CHELSEA_TOKEN
          MONIKER: chelsea
      - task: docker-release-val
        vars:
          TOKEN: $DOPPLER_VAL_MASON_TOKEN
          MONIKER: mason

  release:sentrys:
    internal: true
    desc: Release sentry docker images
    cmds:
      - task: docker-release-sentry
        vars:
          TOKEN: $DOPPLER_SNT_BROOKLYN_TOKEN
          MONIKER: brooklyn
      - task: docker-release-sentry
        vars:
          TOKEN: $DOPPLER_SNT_CHELSEA_TOKEN
          MONIKER: chelsea
      - task: docker-release-sentry
        vars:
          TOKEN: $DOPPLER_SNT_MASON_TOKEN
          MONIKER: mason

  release:deps:
    internal: true
    desc: Release support dependencies
    cmds:
      - task: docker-release-deps
        vars:
          IMAGE: tkms
      - task: docker-release
        vars:
          IMAGE: sonr-faucet

# ------------------------------------------------------------------------------
# -- Internal Tasks ------------------------------------------------------------
# ------------------------------------------------------------------------------
  docker-release:
    silent: true
    internal: true
    desc: Build, tag and push the docker image
    cmds:
      - docker build -f ./Dockerfile . --no-cache --target {{.IMAGE}} -t {{.IMAGE}}
      - docker tag {{.IMAGE}} {{.REGISTRY}}/{{.IMAGE}}:latest
      - docker tag {{.IMAGE}} {{.REGISTRY}}/{{.IMAGE}}:{{.VERSION}}
      - docker tag {{.IMAGE}} {{.REGISTRY}}/{{.IMAGE}}:{{.COMMIT}}
      - docker push {{.REGISTRY}}/{{.IMAGE}}:latest
      - docker push {{.REGISTRY}}/{{.IMAGE}}:{{.VERSION}}
      - docker push {{.REGISTRY}}/{{.IMAGE}}:{{.COMMIT}}
    requires:
      vars: [IMAGE]

  docker-release-deps:
    silent: true
    internal: true
    desc: Build, tag and push the docker image
    cmds:
      - docker build -f ./Dockerfile.deps . --no-cache --target {{.IMAGE}} -t {{.IMAGE}}
      - docker tag {{.IMAGE}} {{.REGISTRY}}/{{.IMAGE}}:latest
      - docker tag {{.IMAGE}} {{.REGISTRY}}/{{.IMAGE}}:{{.VERSION}}
      - docker tag {{.IMAGE}} {{.REGISTRY}}/{{.IMAGE}}:{{.COMMIT}}
      - docker push {{.REGISTRY}}/{{.IMAGE}}:latest
      - docker push {{.REGISTRY}}/{{.IMAGE}}:{{.VERSION}}
      - docker push {{.REGISTRY}}/{{.IMAGE}}:{{.COMMIT}}
    requires:
      vars: [IMAGE]

  docker-release-val:
    silent: true
    internal: true
    desc: Build, tag and push the docker image
    cmds:
      - docker build --build-arg "DOPPLER_TOKEN={{.TOKEN}}" -f ./Dockerfile.prod . --no-cache --target sonr-validator -t sonr-val-{{.MONIKER}}
      - docker tag sonr-val-{{.MONIKER}} {{.REGISTRY}}/sonr-val-{{.MONIKER}}:latest
      - docker tag sonr-val-{{.MONIKER}} {{.REGISTRY}}/sonr-val-{{.MONIKER}}:{{.VERSION}}
      - docker tag sonr-val-{{.MONIKER}} {{.REGISTRY}}/sonr-val-{{.MONIKER}}:{{.COMMIT}}
      - docker push {{.REGISTRY}}/sonr-val-{{.MONIKER}}:latest
      - docker push {{.REGISTRY}}/sonr-val-{{.MONIKER}}:{{.VERSION}}
      - docker push {{.REGISTRY}}/sonr-val-{{.MONIKER}}:{{.COMMIT}}
    requires:
      vars: [TOKEN, MONIKER]

  docker-release-node:
    silent: true
    internal: true
    desc: Build, tag and push the docker image
    cmds:
      - docker build --build-arg "DOPPLER_TOKEN={{.TOKEN}}" -f ./Dockerfile.prod . --no-cache --target sonr-validator -t sonr-node-{{.MONIKER}}
      - docker tag sonr-node-{{.MONIKER}} {{.REGISTRY}}/sonr-node-{{.MONIKER}}:latest
      - docker tag sonr-node-{{.MONIKER}} {{.REGISTRY}}/sonr-node-{{.MONIKER}}:{{.VERSION}}
      - docker tag sonr-node-{{.MONIKER}} {{.REGISTRY}}/sonr-node-{{.MONIKER}}:{{.COMMIT}}
      - docker push {{.REGISTRY}}/sonr-node-{{.MONIKER}}:latest
      - docker push {{.REGISTRY}}/sonr-node-{{.MONIKER}}:{{.VERSION}}
      - docker push {{.REGISTRY}}/sonr-node-{{.MONIKER}}:{{.COMMIT}}
    requires:
      vars: [TOKEN, MONIKER]

  docker-release-sentry:
    silent: true
    internal: true
    desc: Build, tag and push the docker image
    cmds:
      - docker build --build-arg "DOPPLER_TOKEN={{.TOKEN}}" -f ./Dockerfile.prod . --no-cache --target sonr-validator -t sonr-sentry-{{.MONIKER}}
      - docker tag sonr-sentry-{{.MONIKER}} {{.REGISTRY}}/sonr-sentry-{{.MONIKER}}:latest
      - docker tag sonr-sentry-{{.MONIKER}} {{.REGISTRY}}/sonr-sentry-{{.MONIKER}}:{{.VERSION}}
      - docker tag sonr-sentry-{{.MONIKER}} {{.REGISTRY}}/sonr-sentry-{{.MONIKER}}:{{.COMMIT}}
      - docker push {{.REGISTRY}}/sonr-sentry-{{.MONIKER}}:latest
      - docker push {{.REGISTRY}}/sonr-sentry-{{.MONIKER}}:{{.VERSION}}
      - docker push {{.REGISTRY}}/sonr-sentry-{{.MONIKER}}:{{.COMMIT}}
    requires:
      vars: [TOKEN, MONIKER]

  go-build:
    silent: true
    internal: true
    desc: Build the go binary
    cmds:
      - mkdir -p ./build/sonrd-{{.OS}}-{{.ARCH}}
      - GOOS={{.OS}} GOARCH={{.ARCH}} go build -o ./build/sonrd-{{.OS}}-{{.ARCH}}/sonrd ./cmd/sonrd
      - cp ./scripts ./build/sonrd-{{.OS}}-{{.ARCH}}/scripts -p
    requires:
      vars: [OS,ARCH]
