version: '3'

tasks:
  build:
    cmd: earthly --no-sat +build

  deploy-ipfs:
    dir: ./rails/kubo
    cmds:
      - task: build
      - docker stack deploy --prune ipfs

  deploy-faucet:
    dir: ./rails/faucet
    cmds:
      - task: build
      - docker stack deploy --prune faucet

  deploy-matrix:
    dir: ./rails/dendrite
    cmds:
      - task: build
      - docker stack deploy --prune matrix

  deploy-testnet:
    dir: ./networks/testnet-1
    cmds:
      - task: build
      - docker stack deploy --prune testnet-1
