gateway:
  port: 8080
  host: localhost
services:
  sonrd:
    grpc:
      port: 26657
      host: localhost
  matrix:
    server: http://localhost:8008
blockchain:
  chain_id: sonr-localnet
  min_gas_fees: 0.000snr
