version: 1
launch:
  environment: development
  chain-id: sonr-localnet-1
  moniker: alice
  val_address: "0x0000000000"
highway:
  enabled: true
  jwt:
    key: "sercrethatmaycontainch@r$32chars"
  api:
    host: "localhost"
    port: 8080
    timeout: 15
  icefirekv:
    host: "db"
    port: 6001
  icefiresql:
    host: "sql"
    port: 23306
node:
  api:
    host: "validator"
    port: 1317
  p2p:
    host: "validator"
    port: 26656
  rpc:
    host: "validator"
    port: 26657
  grpc:
    host: "validator"
    port: 9090
genesis:
  accounts:
    - name: alice
      coins:
        - 20000snr
        - 200000000usnr
    - name: bob
      coins:
        - 10000snr
        - 100000000usnr
  faucet:
    name: bob
    coins:
      - 5snr
      - 10000000usnr
  validators:
    - name: alice
      bonded: 100000000usnr
