version: "3"
networks:
  sonr-net: {}
services:
  # Sonr Faucet
  faucet:
   container_name: faucet
   hostname: faucet
   image: faucet-runner:latest
   ports:
     - 3000:3000 # rest

  # Cloudflared Reverse Proxy
  reverse-proxy:
   image: cloudflared-runner:latest
   depends_on:
     - ipfs
     - faucet
     - dendrite
     - sonrd
   expose:
     - 80
     - 443
     - 8080
