version: "3"
networks:
  sonr-net: {}
services:
  # Cloudflared Reverse Proxy
  reverse-proxy:
   image: cloudflared-runner:latest
   depends_on:
     - ipfs
     - faucet
     - dendrite
     - sonrd
   expose:
     - 80
     - 443
     - 8080

  # Sonr Validator
  sonrd:
    init: true
    container_name: sonrd
    hostname: sonrd
    image: sonrd-runner:latest
    command: ["start"]
    volumes:
     - /mnt/vol_sonr:/root/.sonr
    ports:
      - 1317:1317 # rest
      - 26657:26657 # rpc
      - 9090:9090 # grpc
    restart: always

  # Sonr Faucet
  faucet:
   container_name: faucet
   hostname: faucet
   image: faucet-runner:latest
   ports:
     - 3000:3000 # rest
