id: "Sonr Events Bridge"
url: "https://matrix.sonr.dev/sonr-events-service"
as_token: "30c05ae90a248a4188e620216fa72e349803310ec83e2a77b34fe90be6081f46"
hs_token: "312df522183efd404ec1cd22d2ffa4bbc76a8c1ccf541dd692eef281356bb74e"
sender_localpart: "_sonr_events" # Will result in @_irc_bot:example.org
namespaces:
  users:
    - exclusive: true
      regex: "@_sonr_events_.*"
  aliases:
    - exclusive: false
      regex: "#_sonr_events_.*"
  rooms: []
