version: v1
managed:
  enabled: true
  go_package_prefix:
    default: github.com/sonrhq/sonr/x/identity/api
    override:
      buf.build/cosmos/cosmos-sdk: cosmossdk.io/api
    except:
      - buf.build/googleapis/googleapis
      - buf.build/cosmos/gogo-proto
      - buf.build/cosmos/cosmos-proto
plugins:
  - name: openapiv2
    out: ../docs/static/swagger
    opt:
      - logtostderr=true
      - openapi_naming_strategy=fqn
      - json_names_for_fields=false
      - generate_unbound_methods=true
