version: "3"

vars:
  VERSION: v0.0.1-test

tasks:

## ------------------------------------------------------------
## Node tasks
## ------------------------------------------------------------
  bind:
    cmds:
      - mkdir -p build
      - task: bind:android
      - task: bind:ios
      - task: bind:wasm
      - mv motorlib-android_arm64 build/motorlib-android_arm64
      - mv motorlib-ios_arm64 build/motorlib-ios_arm64
      - mv motorlib-js-wasm build/motorlib-js-wasm
      - mv build ../build

  bind:android:
    dir: motor-mobile
    cmds:
      - mkdir motorlib-android_arm64
      - gomobile bind -ldflags='-s -w' -target=android/arm64 -o motorlib-android_arm64/io.sonr.motor.aar -v
      - rm -rf motorlib-android_arm64/io.sonr.motor-sources.jar
      - mv motorlib-android_arm64 ../motorlib-android_arm64

  bind:ios:
    dir: motor-mobile
    cmds:
      - mkdir motorlib-ios_arm64
      - gomobile bind -ldflags='-s -w' -target=ios/arm64 -o motorlib-ios_arm64/SonrMotor.xcframework -v
      - mv motorlib-ios_arm64 ../motorlib-ios_arm64

  bind:wasm:
    dir: motor-wasm
    cmds:
      - mkdir motorlib-js_wasm
      - GOOS=js GOARCH=wasm go build -tags wasm -o motorlib-js_wasm/sonr-motor.wasm -v
      - mv motorlib-js_wasm ../motorlib-js_wasm
