version: "3"

vars:
  VERSION: v0.0.1-test

tasks:
  ## ------------------------------------------------------------
  ## Node tasks
  ## ------------------------------------------------------------
  bind:
    cmds:
      - task: clean
      - task: bind:wasm
      - task: bind:ios
      - task: bind:android
      - mv build ../build

  bind:android:
    dir: motor-mobile
    cmds:
      - mkdir motorlib-android
      - gomobile bind -ldflags='-s -w' -target=android/arm64 -o motorlib-android/io.sonr.motor.aar -v
      - rm -rf motorlib-android/io.sonr.motor-sources.jar
      - mv motorlib-android ../build/motorlib-android

  bind:ios:
    dir: motor-mobile
    cmds:
      - mkdir motorlib-ios
      - gomobile bind -ldflags='-s -w' -target=ios -o motorlib-ios/SonrMotor.xcframework -v
      - mv motorlib-ios ../build/motorlib-ios

  bind:wasm:
    dir: motor-wasm
    cmds:
      - mkdir motorlib-wasm
      - GOOS=js GOARCH=wasm go build -tags wasm -o motorlib-wasm/sonr-motor.wasm -v
      - mv motorlib-wasm ../build/motorlib-wasm

  bind:clean:
    cmds:
      - find ./ -type d -name "motorlib-ios" -exec rm -rf {} +
      - find ./ -type d -name "motorlib-wasm" -exec rm -rf {} +
      - find ./ -type d -name "motorlib-android" -exec rm -rf {} +
      - find ./ -type d -name "build" -exec rm -rf {} +
      - mkdir -p build
