version: "3"

tasks:
  docusaurus:
    cmds:
      - echo "yarn docusaurus..."
      - yarn docusaurus
    silent: true

  start:
    cmds:
      - echo "yarn start..."
      - yarn start
    silent: true

  build:
    cmds:
      - echo "yarn build..."
      - yarn build

  swizzle:
    cmds:
      - echo "yarn swizzle..."
      - yarn swizzle
    silent: true

  deploy:
    cmds:
      - echo "yarn deploy..."
      - yarn deploy
    silent: true

  clear:
    cmds:
      - echo "yarn clear..."
      - yarn clear
    silent: true

  serve:
    cmds:
      - echo "yarn serve..."
      - yarn serve
    silent: true

