
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  # name: sonr
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Sonr is a DID Protocol for Cosmos # 79 char long summary
  description: |
    Sonr is a peer-to-peer identity and asset management system that leverages DID documents, Webauthn, and IPFS — providing users with a secure, user-friendly way to manage their digital identity and assets.

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  
