root = "."
tmp_dir = "tmp"

[build]
  bin = "./bin/sonrd"
  cmd = "task build"
  delay = 1000
  exclude_dir = ["static", "tmp", "vendor", "scripts", ".github", ".vscode"]
  exclude_file = []
  exclude_regex = [".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "./bin/sonrd serve"
  include_dir = ["pkg/nebula", "app/highway"]
  include_ext = ["go", "tpl", "tmpl", "templ", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true
