version: "3"
networks:
  tunnel:
    external: true

services:
  # Cloudflared Reverse Proxy
  cloudflared:
    image: erisamoe/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${MATRIX_TUNNEL_TOKEN}
    networks:
      - tunnel

  # Matrix Homeserver
  dendrite:
    init: true
    container_name: dendrite
    hostname: dendrite
    image: dendrite-runner:latest
    ports:
      - 8008:8008 # rest
      - 8448:8448 # e2e
    volumes:
     - /mnt/vol_dendrite:/etc/dendrite
    networks:
     - tunnel
