name: Buf.build Workflow

on:
  push:
    tags:
      - v*

jobs:
 publish-buf-build:
    name: "Publish Buf.build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: 'latest'
      - uses: bufbuild/buf-push-action@v1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
