# This workflow builds the sonrd binary for amd64 and arm64 on Darwin and Linux.
#
# This workflow runs:
# - on pushes to main
# - on every pull requests
# - when manually triggered
#
# Caching strategy
# This code will store the Go modules cache based on the hash of your go.sum file,
# ensuring that the cache will be invalidated when your dependencies change.
# The cache will be stored on a per-branch basis, which should prevent cache pollution issues between different branches.

name: Build

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "v[0-9]**"
      - "**"
  workflow_dispatch:
  merge_group:
env:
  GO_VERSION: "1.20.5"
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-default:
    name: Build sonrd-${{ matrix.targetos }}-${{ matrix.arch }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, arm64]
        targetos: [darwin, linux]
        include:
          - targetos: darwin
            arch: arm64

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install nix
        uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install bob
        run: curl -L https://bob.build/install.sh | BIN_DIR=/usr/local/bin sh

      - name: Bob build
        run: bob build
