name: PR Merged to Master -> Run CD
on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    types:
      - closed
    branches:
      - master
  release:
    types: [published]

jobs:
  run-goreleaser:
    name: Publish Release with GoReleaser
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.5'
      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_PAT }}
