name: New Release on Master -> Run CD

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  deploy-stack:
    runs-on: self-hosted
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v4
      - run: earthly +deploy

  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: BobAnkh/auto-generate-changelog@v1.2.5
        with:
          REPO_NAME: sonrhq/sonr
          ACCESS_TOKEN: ${{secrets.GH_ACTIONS_PAT}}
          PATH: "CHANGELOG.md"
          COMMIT_MESSAGE: "docs: update release notes"
          TYPE: "feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,test:Tests,chore:Chore,init:Setup"
          COMMITTER: "Sonr Mind <ai@sonr.io)"
          SUPPRESS_UNSCOPED: true
          REGENERATE_COUNT: 12

  announce:
    runs-on: ubuntu-latest
    needs: [deploy-stack,changelog]
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.7.10
      - uses: actions/checkout@v4
