name: Master Branch += PR -> Run CD
on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  publish-release:
    name: Publish Go Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.21'
      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_PAT }}
