name: New Release / Prad Pushed to Origin -> Run CD

on:
  release:
    types: [published]
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  run-goreleaser:
    name: Run GoReleaser
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_PAT }}

  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    if: github.event_name =='release'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: BobAnkh/auto-generate-changelog@v1.2.5
        with:
          REPO_NAME: sonrhq/sonr
          ACCESS_TOKEN: ${{secrets.GH_ACTIONS_PAT}}
          PATH: "CHANGELOG.md"
          COMMIT_MESSAGE: "docs: update release notes"
          TYPE: "feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,test:Tests,chore:Chore,init:Setup"
          COMMITTER: "Sonr Mind <ai@sonr.io)"
          SUPPRESS_UNSCOPED: true
          REGENERATE_COUNT: 12
