name: Generate changelog
on:
  workflow_dispatch:
  release:
    types: [created, edited]

permissions:
  contents: write

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: BobAnkh/auto-generate-changelog@v1.2.5
        with:
          REPO_NAME: sonrhq/core
          ACCESS_TOKEN: ${{secrets.GH_CORE_CHANGELOG_TOKEN}}
          PATH: "CHANGELOG.md"
          COMMIT_MESSAGE: "docs(CHANGELOG): update release notes"
          TYPE: "'* feat':Feature,'* fix':Bug Fixes,'* docs':Documentation,'* refactor':Refactor,'* test':Tests"
          COMMITTER: "sOnr mInd <ai@sonr.io)"
          SUPPRESS_UNSCOPED: true
          REGENERATE_COUNT: -1
