name: Generate Changelog

on:
  release:
    types:
      - published

jobs:
  generate_changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install openai
        pip install PyGithub

    - name: Generate Changelog
      id: generate_changelog
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python .github/scripts/generate_changelog.py

    - name: Update Release Body
      uses: ncipollo/release-action@v1
      with:
        draft: false
        prerelease: false
        body: ${{ steps.generate_changelog.outputs.changelog }}
        GITHUB_TOKEN: ${{ secrets.CR_GH_PAT }}
