name: Add GPT summary to PR descriptin
on: [issue_comment]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - name: listen for PR Comments
        uses: machine-learning-apps/actions-chatops@master
        with:
          TRIGGER_PHRASE: "GPT summary"
        env: # you must supply GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.CR_GH_PAT }}
        id: prcomm
        # This step clones the branch of the PR associated with the triggering phrase, but only if it is triggered.
      - name: edit-pull-request-description
        uses: Jerome1337/comment-pull-request@v1.0.4
        env: # you must supply GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.CR_GH_PAT }}
        with:
          pull_request_number: ${{ steps.prcomm.outputs.PULL_REQUEST_NUMBER }}
