name: Merge Queue += PR -> Run CI

on:
  merge_group:

permissions:
  contents: write
  packages: write
  pull-requests: write
  issues: write

jobs:
  valid-protobufs:
    name: Validate Protos
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.7.10
      - uses: actions/checkout@v4
      - run: earthly --sat=tester +breaking

  release-build-test:
    name: Run Go Build Test
    needs: [valid-protobufs]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.5'
      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: build --snapshot
