name: New Pull Request -> Run CI

on:
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:
  push:
    tags:
      - '*'

permissions:
  contents: write
  packages: write
  pull-requests: write
  issues: write

jobs:
  run-lints:
    name: Validate Protos
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.7.10
      - uses: actions/checkout@v4
      - run: earthly --sat=tester +breaking
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GH_ACTIONS_PAT }}"

  validate-pr:
    name: Validate PR Labels
    runs-on: ubuntu-latest
    if: github.event_name == 'merge_group'
    environment: Staging
    needs: [run-lints]
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v4
      - uses: jefflinse/pr-semver-bump@v1.6.0
        name: Validate Pull Request Metadata
        with:
          mode: validate
          repo-token: ${{ secrets.GH_ACTIONS_PAT }}
          major-label: 'Breaking Changes'
          minor-label: 'Patch'
          require-release-notes: false
          with-v: true

  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'merge_group'
    environment: Staging
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.7.10
      - uses: actions/checkout@v4
      - run: earthly --sat=tester +test

  run-goreleaser:
    name: Run GoReleaser
    runs-on: ubuntu-latest
    environment: Staging
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GH_ACTIONS_PAT }}
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_PAT }}
