name: Added to Merge Queue -> Run CI

on:
  merge_group:
    types: [checks_requested]

jobs:
  bump-tag:
    runs-on: ubuntu-latest
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v4
      - uses: jefflinse/pr-semver-bump@v1.6.0
        name: Bump and Tag Version
        id: pr-semver-bump
        with:
          mode: bump
          repo-token: ${{ secrets.GH_ACTIONS_PAT }}
          major-label: '@Major-Release'
          minor-label: '@Minor-Release'
          patch-label: '@Patch-Release'
          noop-labels: 'Community'
          require-release-notes: false
          release-notes-prefix: ''
          release-notes-suffix: ''
          with-v: true
          base-branch: false
    outputs:
      version: ${{ steps.pr-semver-bump.outputs.version }}
      old-version: ${{ steps.pr-semver-bump.outputs.old-version }}
      skipped: ${{ steps.pr-semver-bump.outputs.skipped }}
