name: CRON Nightly

on:
  schedule:
    - cron: "0 2 * * *"

permissions:
  contents: write
  packages: write
  pull-requests: write
  issues: write

jobs:
  release-nightly:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.21"
      - name: Install Dependencies
        run: |
          go install github.com/charmbracelet/mods@latest
          go install github.com/go-task/task/v3/cmd/task@latest

      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser-pro
          version: latest
          args: release --nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_PAT }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  analyze-codeql:
    name: Analyze
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
    permissions:
      security-events: write
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        language: ["go"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"

  test-crypto-accumulator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.5"
      - run: |
          go install github.com/go-task/task/v3/cmd/task@latest
          task test:crypto-accumulator

  test-crypto-daed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.5"
      - run: |
          go install github.com/go-task/task/v3/cmd/task@latest
          task test:crypto-daed

  test-crypto-ecies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.5"
      - run: |
          go install github.com/go-task/task/v3/cmd/task@latest
          task test:crypto-ecies

  test-crypto-sharing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.5"
      - run: |
          go install github.com/go-task/task/v3/cmd/task@latest
          task test:crypto-sharing

  test-crypto-signatures:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.5"
      - run: |
          go install github.com/go-task/task/v3/cmd/task@latest
          task test:crypto-signatures

  test-crypto-tecdsa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.5"
      - run: |
          go install github.com/go-task/task/v3/cmd/task@latest
          task test:crypto-tecdsa
