name: "🗑️ Delete old workflow runs"
on:
  schedule:
    - cron: "0 2 * * *" # run at 2 AM UTC
  workflow_dispatch:

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.CR_GH_PAT }}
          repository: ${{ github.repository }}
          retain_days: "7"
          keep_minimum_runs: "1"
          delete_workflow_by_state_pattern: "All"
          delete_run_by_conclusion_pattern: "All"
