name: Prad Pushes to Origin -> Run CD Devnet

on:
  push:

permissions:
  contents: write

jobs:
  deploy-devnet:
    name: Deploy Devnet
    runs-on: self-hosted
    environment: Devnet
    if: github.actor == 'prnk28'
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v4
      - run: echo "Fix me ."
