name: Deploy Docs to GitHub Pages

on:
  push:
    tags:
      - v*


jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./docs

      - name: Build website
        run: yarn build
        working-directory: ./docs

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_GH_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./docs/build
