name: Daily 🡒 Release Nightly

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write
  packages: write
  pull-requests: write
  issues: write

jobs:
  release-nightly:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.21'
      - name: Install Dependencies
        run: |
          go install github.com/charmbracelet/mods@latest
          go install github.com/go-task/task/v3/cmd/task@latest
      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser-pro
          version: latest
          args: release --nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_PAT }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
