name: New Pull Request -> Lint, Test, Analyze

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  packages: write
  pull-requests: write
  issues: write

jobs:
  validate-protos:
    runs-on: ubuntu-latest
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - uses: pnorton5432/setup-task@v1
      - uses: earthly/actions-setup@v1
        with:
          version: v0.7.10
      - uses: actions/checkout@v4

  run-tests:
    runs-on: ubuntu-latest
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - uses: pnorton5432/setup-task@v1
      - uses: earthly/actions-setup@v1
        with:
          version: v0.7.10
      - uses: actions/checkout@v4
      - run: task tests

  analyze-pull:
    runs-on: ubuntu-latest
    needs: [validate-protos]
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GH_ACTIONS_PAT }}"
      - uses: jefflinse/pr-semver-bump@v1.6.0
        name: Validate Pull Request Metadata
        with:
          mode: validate
          repo-token: ${{ secrets.GH_ACTIONS_PAT }}
          major-label: '@Major-Release'
          minor-label: '@Minor-Release'
          patch-label: '@Patch-Release'
          noop-labels: 'Community'
          require-release-notes: false
          release-notes-prefix: ''
          release-notes-suffix: ''
          with-v: true
          base-branch: false

  add-to-merge-queue:
    runs-on: ubuntu-latest
    needs: [run-tests, analyze-pull]
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v4
      - run: gh pr merge ${{ github.event.pull_request.number }}
