name: Publish Releases

on:
  schedule:
    - cron: "0 17 * * *" # 9 AM PST is 17:00 UTC

jobs:
  publish-drafts:
    runs-on: ubuntu-super
    steps:
      - name: Publish Drafts
        run: |
          yesterday=$(date -u -d "yesterday" +"%Y-%m-%d")
          drafts=$(gh release list --json createdAt,draft -q "map(select(.draft==true and .createdAt >= '$yesterday')) | .[].name")
          for draft in $drafts; do
            gh release update $draft --draft false
          done
