# This workflow creates a release using goreleaser
# via the 'make release' command.

name: Create release

on:
  workflow_dispatch:
  push:
    tags:
      - v*
permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  release:
    name: Create release
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Run only on tag
      - run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-docker:
    name: Push release images
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Run only on tag
      - run: make release-docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-binaries:
    name: Create release binaries
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Run only on tag
      - run: make release-binaries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          make release-binaries

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.releaser.outputs.next_version }}
          token: ${{ secrets.CR_GH_PAT }}
          files: |
            dist/*
