name: Release Workflow

on:
  push:
    tags:
      - v*

jobs:
  run-goreleaser:
    name: "Release All Binaries and Frameworks"
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Homebrew w/ cache
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/Homebrew/foo--*
            ~/Library/Caches/Homebrew/downloads/*--foo-*
          key: brew-${{ hashFiles('.github/brew-formulae') }}
          restore-keys: brew-
      - name: Install Homebrew dependencies
        run: |
          brew install FiloSottile/musl-cross/musl-cross
          brew install mingw-w64

      - name: Configure Golang w/ cache
        uses: magnetikonline/action-golang-cache@v2
        with:
          go-version: ~1.17
      # - name: Install dependencies
      #   run: |
      #     go install golang.org/x/mobile/cmd/gomobile@latest
      #     gomobile init
      #   working-directory: ${{ github.workspace }}/bind/motor-mobile


      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser-pro
          version: latest
          args: release --rm-dist --parallelism=4
        env:
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          GITHUB_TOKEN: ${{ secrets.ACTIONS_GH_TOKEN }}

      # - name: motor-ios Repository Dispatch
      #   uses: peter-evans/repository-dispatch@v2
      #   with:
      #     token: ${{ secrets.ACTIONS_GH_TOKEN }}
      #     repository: sonr-io/motor-ios
      #     event-type: new-ios-framework
      #     client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

      # - name: motor-android Repository Dispatch
      #   uses: peter-evans/repository-dispatch@v2
      #   with:
      #     token: ${{ secrets.ACTIONS_GH_TOKEN }}
      #     repository: sonr-io/motor-android
      #     event-type: new-android-framework
      #     client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
