name: Branch Merged to Master -> Create Release

on:
  pull_request_target:
    types:
      - closed

permissions:
  contents: write
  issues: read
  pull-requests: read

jobs:
  publish-images:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref =='main'
    name: Publish Docker Images
    runs-on: ubuntu-latest
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
    steps:
      - uses: pnorton5432/setup-task@v1
      - uses: earthly/actions-setup@v1
        with:
          version: v0.7.10
      - uses: actions/checkout@v4
      - run: task publish
