name: Run Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  pull-requests: write
  issues: write

jobs:
  test-breaking:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: buf.build/sonrhq/sonr

  test-crypto:
    environment: Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.5"
      - run: |
          go install github.com/go-task/task/v3/cmd/task@latest
          task test:crypto

  test-identity:
    environment: Staging
    runs-on: ubuntu-latest
    needs: [test-breaking]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.5"
      - run: |
          go install github.com/go-task/task/v3/cmd/task@latest
          task test:module-identity

  test-service:
    environment: Staging
    runs-on: ubuntu-latest
    needs: [test-breaking]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.5"
      - run: |
          go install github.com/go-task/task/v3/cmd/task@latest
          task test:module-service
