name: "Triage Issues"
on:
  push:
    branches-ignore:
      - master
  issues:
    types: [opened, edited]

permissions:
  contents: write
  packages: write
  pull-requests: write
  issues: write

jobs:
  label-issues:
    runs-on: "ubuntu-latest"
    if: contains(github.event, 'issues')
    steps:
      - uses: "actions/checkout@v3"
      - uses: austenstone/openai-issue-labeler@v2
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
