name: "Triage Issues"
on:
  push:
  issues:
    types: [opened, edited]

permissions:
  contents: write
  packages: write
  pull-requests: write
  issues: write

jobs:
  add-issues:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_PAT }}

  label-issues:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: satoryu/labeling-by-gpt@main
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          github-token: ${{ secrets.GH_ACTIONS_PAT }}
