name: "Publish to Vercel"
on:
  create:
    tags:
      - v*
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST -d {} https://api.vercel.com/v1/integrations/deploy/prj_7Tfshwh5WL744ND8BaQsgjI5R0vw/YH9p5F6Fe0
