yarnPath: .yarn/releases/yarn-3.3.1.cjs
npmScopes:
  buf:
    npmRegistryServer: https://buf.build/gen/npm/v1
  saas-ui:
    npmRegistryServer: "https://npm.saas-ui.dev"
npmRegistries:
  //npm.saas-ui.dev:
    npmAuthIdent: "${SAAS_UI_TOKEN:-}"
    npmAlwaysAuth: true
